/**
 * QuizAssignmentSettingsModal — edit the settings for a single assignment.
 *
 * Wave 2-QZ: this component now composes the shared `AssignModal` primitive
 * with the PLC selector rendered into `plcSlot` and the quiz-specific toggles
 * (Quiz Integrity / Answer Feedback / Gamification) rendered into
 * `extraSlot`. The behavior is preserved 1:1 from the previous implementation
 * — mode is editable only when the assignment is inactive, all PLC fields
 * are persisted verbatim (including empty strings so clearing a field
 * actually writes ''), and the save patch shape is unchanged.
 */

import React, { useState } from 'react';
import { AlertTriangle, Lock, User, Zap, Clock, Share2 } from 'lucide-react';
import type {
  QuizAssignment,
  QuizAssignmentSettings,
  QuizSessionMode,
  QuizSessionOptions,
  ClassRoster,
} from '@/types';
import { Toggle } from '@/components/common/Toggle';
import { AttemptLimitRow } from './AttemptLimitRow';
import {
  AssignModal,
  CollapsibleSection,
  type AssignModeOption,
} from '@/components/common/library';

interface QuizAssignmentSettingsModalProps {
  assignment: QuizAssignment;
  rosters: ClassRoster[];
  onClose: () => void;
  onSave: (patch: Partial<QuizAssignmentSettings>) => Promise<void> | void;
  /**
   * Signed-in teacher's display name. Used as the auto-fill default for the
   * "Your Name" / `teacherName` field when the assignment itself doesn't
   * carry one — applies to fresh assignments and to imports of shared PLC
   * assignments (the importer's row of the shared sheet should be labelled
   * with their own name, not the originator's).
   */
  defaultTeacherName?: string;
}

/** Options object driven through AssignModal's `options` generic. */
interface SettingsOptions {
  className: string;
  tabWarningsEnabled: boolean;
  showResultToStudent: boolean;
  showCorrectAnswerToStudent: boolean;
  showCorrectOnBoard: boolean;
  speedBonusEnabled: boolean;
  streakBonusEnabled: boolean;
  showPodiumBetweenQuestions: boolean;
  soundEffectsEnabled: boolean;
  /** null = unlimited; any positive int = hard cap. */
  attemptLimit: number | null;
  plcMode: boolean;
  teacherName: string;
  selectedPeriodNames: string[];
  plcSheetUrl: string;
}

function initialOptionsFor(
  a: QuizAssignment,
  defaultTeacherName?: string
): SettingsOptions {
  const opts = a.sessionOptions ?? {};
  return {
    className: a.className ?? '',
    tabWarningsEnabled: opts.tabWarningsEnabled ?? true,
    showResultToStudent: opts.showResultToStudent ?? false,
    showCorrectAnswerToStudent: opts.showCorrectAnswerToStudent ?? false,
    showCorrectOnBoard: opts.showCorrectOnBoard ?? false,
    speedBonusEnabled: opts.speedBonusEnabled ?? false,
    streakBonusEnabled: opts.streakBonusEnabled ?? false,
    showPodiumBetweenQuestions: opts.showPodiumBetweenQuestions ?? false,
    soundEffectsEnabled: opts.soundEffectsEnabled ?? false,
    // Legacy assignments have no attemptLimit — preserve "unlimited" for
    // those rather than retroactively capping ongoing sessions.
    attemptLimit: a.attemptLimit ?? null,
    plcMode: !!a.plc,
    teacherName: a.teacherName ?? defaultTeacherName ?? '',
    selectedPeriodNames: a.periodNames ?? (a.periodName ? [a.periodName] : []),
    plcSheetUrl: a.plc?.sheetUrl ?? '',
  };
}

/* ─── Mode selector options ───────────────────────────────────────────────── */

const MODES_BASE: Omit<AssignModeOption, 'disabled'>[] = [
  {
    id: 'teacher',
    label: 'Teacher-paced',
    description: 'You control when to move to the next question.',
    icon: User,
  },
  {
    id: 'auto',
    label: 'Auto-progress',
    description: 'Moves automatically once everyone has answered.',
    icon: Zap,
  },
  {
    id: 'student',
    label: 'Self-paced',
    description: 'Students move through questions at their own speed.',
    icon: Clock,
  },
];

export const QuizAssignmentSettingsModal: React.FC<
  QuizAssignmentSettingsModalProps
> = ({ assignment, rosters, onClose, onSave, defaultTeacherName }) => {
  // Mode is only editable when the assignment is inactive — changing it
  // mid-session would leave the live session in an incoherent state.
  const modeLocked = assignment.status !== 'inactive';

  const [options, setOptions] = useState<SettingsOptions>(() =>
    initialOptionsFor(assignment, defaultTeacherName)
  );
  const [sessionMode, setSessionMode] = useState<QuizSessionMode>(
    assignment.sessionMode
  );

  // "Auto-Generated PLC Sheet" toggle — defaults ON when:
  //   (a) the linkage was created by the system (`plc.autoGenerated === true`,
  //       set at create time in Widget.tsx and preserved through PLC peer
  //       imports) — this keeps Teacher B's view consistent with Teacher A's
  //       intent and hides the URL field since the system manages it, OR
  //   (b) no URL is attached yet (fresh PLC mode opt-in).
  // Legacy / manually pasted assignments (no `autoGenerated` flag, sheetUrl
  // present) open with the toggle OFF and the URL pre-filled so the user
  // can keep using or edit it. Edit mode never triggers auto-create on
  // save — toggling ON simply hides the field; the existing
  // `assignment.plc.sheetUrl` is preserved by the no-op branch in
  // `handleAssign` when `plcSheetUrl` saves as empty.
  const [useAutoGenerated, setUseAutoGenerated] = useState(
    assignment.plc?.autoGenerated === true || !assignment.plc?.sheetUrl
  );

  const plcSheetUrlInvalid =
    !!options.plcSheetUrl &&
    !options.plcSheetUrl.startsWith('https://docs.google.com/spreadsheets/');

  const modes: AssignModeOption[] = MODES_BASE.map((m) => ({
    ...m,
    disabled: modeLocked,
  }));

  const handleAssign = async () => {
    const sessionOptions: QuizSessionOptions = {
      tabWarningsEnabled: options.tabWarningsEnabled,
      showResultToStudent: options.showResultToStudent,
      showCorrectAnswerToStudent: options.showCorrectAnswerToStudent,
      showCorrectOnBoard: options.showCorrectOnBoard,
      speedBonusEnabled: options.speedBonusEnabled,
      streakBonusEnabled: options.streakBonusEnabled,
      showPodiumBetweenQuestions: options.showPodiumBetweenQuestions,
      soundEffectsEnabled: options.soundEffectsEnabled,
    };
    // Intentionally pass empty strings (not undefined) so that clearing a
    // field actually writes '' to Firestore. Using `|| undefined` would cause
    // updateDoc to skip the field and leave the previous value in place.
    //
    // PLC linkage rebuild rules: when the toggle is on, carry the current
    // linkage's id/name/memberEmails through and overlay the (possibly
    // edited) sheet URL. When off, write `undefined` to clear the linkage
    // entirely. The current `assignment.plc` is the safe carrier — it was
    // either set at create time (Widget.tsx → createAssignment) or by a
    // prior save through this modal.
    // Only patch `plc` when we have a real existing linkage to overlay onto.
    // Toggling PLC mode on without an `assignment.plc` record would persist
    // a placeholder with empty `id`/`name`, which downstream code treats as
    // a valid PLC linkage — that breaks sharing/membership checks and sheet
    // export. The teacher should re-run assignment-create to acquire a real
    // linkage. (Copilot review on PR #1442.)
    //
    // Empty `trimmedSheetUrl` is a Hide / cancel: the user collapsed the
    // manual-attach disclosure, which clears the form input. We keep the
    // assignment's existing `plc` unchanged rather than overwriting
    // `sheetUrl` with `''` — the empty value would be dropped by the
    // read-side validator on next snapshot and silently lose PLC mode.
    const trimmedSheetUrl = options.plcSheetUrl.trim();
    const plcPatch: QuizAssignmentSettings['plc'] =
      options.plcMode && assignment.plc
        ? trimmedSheetUrl === ''
          ? assignment.plc
          : { ...assignment.plc, sheetUrl: trimmedSheetUrl }
        : undefined;
    const patch: Partial<QuizAssignmentSettings> = {
      className: options.className.trim(),
      sessionMode: modeLocked ? assignment.sessionMode : sessionMode,
      sessionOptions,
      attemptLimit: options.attemptLimit,
      plc: plcPatch,
      teacherName: options.teacherName.trim(),
      periodName: options.selectedPeriodNames[0] ?? '',
      periodNames: options.selectedPeriodNames,
    };
    try {
      await onSave(patch);
      onClose();
    } catch (err) {
      if (import.meta.env.DEV)
        console.error('[QuizAssignmentSettingsModal] save failed:', err);
    }
  };

  return (
    <AssignModal<SettingsOptions>
      isOpen
      onClose={onClose}
      itemTitle={assignment.quizTitle}
      modes={modes}
      selectedMode={sessionMode}
      onModeChange={(id) => {
        if (modeLocked) return;
        setSessionMode(id as QuizSessionMode);
      }}
      options={options}
      onOptionsChange={setOptions}
      assignmentName={options.className}
      onAssignmentNameChange={(v) =>
        setOptions((prev) => ({ ...prev, className: v }))
      }
      confirmLabel="Save"
      onAssign={handleAssign}
      extraSlot={
        <>
          {modeLocked && (
            <div className="flex items-center gap-1.5 text-xxs font-bold text-slate-400 uppercase tracking-widest -mt-2">
              <Lock className="w-3 h-3" />
              Session mode locked
              <span className="font-normal text-slate-400 normal-case tracking-normal">
                — make this assignment inactive to change it.
              </span>
            </div>
          )}

          <SectionHeader label="Quiz Integrity" />
          <AttemptLimitRow
            value={options.attemptLimit}
            onChange={(v) => setOptions((p) => ({ ...p, attemptLimit: v }))}
          />
          <ToggleRow
            label="Tab Switch Detection"
            checked={options.tabWarningsEnabled}
            onChange={(v) =>
              setOptions((p) => ({ ...p, tabWarningsEnabled: v }))
            }
            hint="Warn students who leave the quiz tab"
          />

          <CollapsibleSection label="Answer Feedback">
            <ToggleRow
              compact
              label="Show right/wrong to students"
              checked={options.showResultToStudent}
              onChange={(v) =>
                setOptions((p) => ({ ...p, showResultToStudent: v }))
              }
              hint="Students see ✓ or ✗ after submitting"
            />
            <ToggleRow
              compact
              label="Reveal correct answer to students"
              checked={options.showCorrectAnswerToStudent}
              onChange={(v) =>
                setOptions((p) => ({ ...p, showCorrectAnswerToStudent: v }))
              }
              disabled={!options.showResultToStudent}
              hint="Also show what the correct answer was"
            />
            <ToggleRow
              compact
              label="Show correct answer on board"
              checked={options.showCorrectOnBoard}
              onChange={(v) =>
                setOptions((p) => ({ ...p, showCorrectOnBoard: v }))
              }
              hint="Display correct answer on the projected screen"
            />
          </CollapsibleSection>

          <CollapsibleSection label="Gamification">
            <ToggleRow
              compact
              label="Speed Bonus Points"
              checked={options.speedBonusEnabled}
              onChange={(v) =>
                setOptions((p) => ({ ...p, speedBonusEnabled: v }))
              }
              hint="Up to 50% bonus for fast answers"
            />
            <ToggleRow
              compact
              label="Streak Bonuses"
              checked={options.streakBonusEnabled}
              onChange={(v) =>
                setOptions((p) => ({ ...p, streakBonusEnabled: v }))
              }
              hint="Multiplier for consecutive correct answers"
            />
            <ToggleRow
              compact
              label="Podium Between Questions"
              checked={options.showPodiumBetweenQuestions}
              onChange={(v) =>
                setOptions((p) => ({ ...p, showPodiumBetweenQuestions: v }))
              }
              hint="Show top 3 leaderboard after each question"
            />
            <ToggleRow
              compact
              label="Sound Effects"
              checked={options.soundEffectsEnabled}
              onChange={(v) =>
                setOptions((p) => ({ ...p, soundEffectsEnabled: v }))
              }
              hint="Chimes, ticks, and fanfares during the quiz"
            />
          </CollapsibleSection>
        </>
      }
      plcSlot={
        <>
          <div className="border-t border-slate-200/70 pt-3 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Share2 className="w-4 h-4 text-brand-blue-primary" />
              <span className="text-sm font-bold text-brand-blue-dark">
                Share with PLC
              </span>
            </div>
            <Toggle
              checked={options.plcMode}
              onChange={(v) => setOptions((p) => ({ ...p, plcMode: v }))}
              size="sm"
              showLabels={true}
            />
          </div>
          <p className="text-xxs text-slate-500 -mt-1">
            Export results to a shared Google Sheet for your PLC team.
          </p>

          <div>
            <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
              Class Periods
            </label>
            {rosters.length > 0 ? (
              <div className="space-y-1.5 max-h-36 overflow-y-auto rounded-lg border border-slate-200 bg-white p-2">
                {rosters.map((r) => {
                  const checked = options.selectedPeriodNames.includes(r.name);
                  return (
                    <label
                      key={r.id}
                      className="flex items-center gap-2 cursor-pointer hover:bg-slate-50 rounded px-1.5 py-1"
                    >
                      <input
                        type="checkbox"
                        checked={checked}
                        onChange={() =>
                          setOptions((p) => ({
                            ...p,
                            selectedPeriodNames: checked
                              ? p.selectedPeriodNames.filter(
                                  (n) => n !== r.name
                                )
                              : [...p.selectedPeriodNames, r.name],
                          }))
                        }
                        className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                      />
                      <span className="text-sm text-slate-800">{r.name}</span>
                    </label>
                  );
                })}
              </div>
            ) : (
              <input
                type="text"
                value={options.selectedPeriodNames.join(', ')}
                onChange={(e) => {
                  const names = e.target.value
                    .split(',')
                    .map((n) => n.trim())
                    .filter(Boolean);
                  setOptions((p) => ({
                    ...p,
                    selectedPeriodNames: [...new Set(names)],
                  }));
                }}
                placeholder="e.g. Period 1, Period 2"
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
            )}
            <p className="text-xxs text-slate-400 mt-0.5">
              Select class periods for this assignment. Students will choose
              their class when joining.
            </p>
          </div>

          {options.plcMode && (
            <div className="space-y-3 bg-slate-50 rounded-xl p-3 border border-slate-100">
              <div>
                <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
                  Your Name
                </label>
                <input
                  type="text"
                  value={options.teacherName}
                  onChange={(e) =>
                    setOptions((p) => ({ ...p, teacherName: e.target.value }))
                  }
                  placeholder="e.g. Ms. Smith"
                  className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
                <p className="text-xxs text-slate-400 mt-0.5">
                  Appears in the &quot;Teacher&quot; column of the shared sheet
                </p>
              </div>

              <ToggleRow
                label="Auto-Generated PLC Sheet"
                checked={useAutoGenerated}
                onChange={(v) => {
                  setUseAutoGenerated(v);
                  if (v) setOptions((p) => ({ ...p, plcSheetUrl: '' }));
                }}
                hint={
                  useAutoGenerated
                    ? 'Auto-create runs at assignment creation. To rebuild this sheet from scratch later, click "Re-export Sheet" on the Results screen.'
                    : 'Paste a Google Sheet URL — useful for pointing this assignment at a sheet you already have.'
                }
              />
              {!useAutoGenerated && (
                <div>
                  <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
                    Shared Google Sheet URL
                  </label>
                  <input
                    type="text"
                    value={options.plcSheetUrl}
                    onChange={(e) =>
                      setOptions((p) => ({ ...p, plcSheetUrl: e.target.value }))
                    }
                    placeholder="https://docs.google.com/spreadsheets/d/..."
                    className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                  {plcSheetUrlInvalid && (
                    <div className="flex items-center gap-1 mt-1 text-amber-600">
                      <AlertTriangle className="w-3 h-3" />
                      <span className="text-xxs">
                        This doesn&apos;t look like a Google Sheets URL
                      </span>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </>
      }
    />
  );
};

/* ─── Local small UI helpers ─────────────────────────────────────────────── */

const SectionHeader: React.FC<{ label: string }> = ({ label }) => (
  <p className="text-xxs font-bold text-brand-blue-primary/60 uppercase tracking-widest pt-1">
    {label}
  </p>
);

const ToggleRow: React.FC<{
  label: string;
  checked: boolean;
  onChange: (v: boolean) => void;
  hint?: string;
  disabled?: boolean;
  /**
   * When true, the label renders in the small uppercase brand-blue style
   * used inside `CollapsibleSection` bodies. Top-level rows (e.g. Tab
   * Switch Detection) use the default bold-dark label.
   */
  compact?: boolean;
}> = ({ label, checked, onChange, hint, disabled, compact = false }) => (
  <div className={disabled ? 'opacity-40 pointer-events-none' : ''}>
    <div className="flex items-center justify-between">
      <span
        className={
          compact
            ? 'text-xxs font-bold text-brand-blue-primary/60 uppercase tracking-widest'
            : 'text-sm font-bold text-brand-blue-dark'
        }
      >
        {label}
      </span>
      <Toggle checked={checked} onChange={onChange} size="sm" showLabels />
    </div>
    {hint && <p className="text-xxs text-slate-500 mt-0.5">{hint}</p>}
  </div>
);
