/**
 * QuizAssignmentSettingsModal — edit the settings for a single assignment.
 *
 * Wave 2-QZ: this component now composes the shared `AssignModal` primitive
 * with the PLC selector rendered into `plcSlot` and the quiz-specific toggles
 * (Quiz Integrity / Answer Feedback / Gamification) rendered into
 * `extraSlot`. The behavior is preserved 1:1 from the previous implementation
 * — mode is editable only when the assignment is inactive, all PLC fields
 * are persisted verbatim (including empty strings so clearing a field
 * actually writes ''), and the save patch shape is unchanged.
 */

import React, { useState } from 'react';
import { AlertTriangle, Share2 } from 'lucide-react';
import type {
  QuizAssignment,
  QuizAssignmentSettings,
  QuizBehaviorSettings,
  QuizSessionMode,
  QuizSessionOptions,
  ClassRoster,
} from '@/types';
import { Toggle } from '@/components/common/Toggle';
import {
  AssignModal,
  ToggleRow,
  QuizBehaviorSettingsPanel,
} from '@/components/common/library';

interface QuizAssignmentSettingsModalProps {
  assignment: QuizAssignment;
  rosters: ClassRoster[];
  onClose: () => void;
  onSave: (patch: Partial<QuizAssignmentSettings>) => Promise<void> | void;
  /**
   * Signed-in teacher's display name. Used as the auto-fill default for the
   * "Your Name" / `teacherName` field when the assignment itself doesn't
   * carry one — applies to fresh assignments and to imports of shared PLC
   * assignments (the importer's row of the shared sheet should be labelled
   * with their own name, not the originator's).
   */
  defaultTeacherName?: string;
}

/** Options object driven through AssignModal's `options` generic. */
interface SettingsOptions {
  className: string;
  tabWarningsEnabled: boolean;
  showResultToStudent: boolean;
  showCorrectAnswerToStudent: boolean;
  showCorrectOnBoard: boolean;
  speedBonusEnabled: boolean;
  streakBonusEnabled: boolean;
  showPodiumBetweenQuestions: boolean;
  soundEffectsEnabled: boolean;
  shuffleQuestions: boolean;
  shuffleAnswerOptions: boolean;
  /** null = unlimited; any positive int = hard cap. */
  attemptLimit: number | null;
  plcMode: boolean;
  teacherName: string;
  selectedPeriodNames: string[];
  plcSheetUrl: string;
}

function initialOptionsFor(
  a: QuizAssignment,
  defaultTeacherName?: string
): SettingsOptions {
  const opts = a.sessionOptions ?? {};
  return {
    className: a.className ?? '',
    tabWarningsEnabled: opts.tabWarningsEnabled ?? true,
    showResultToStudent: opts.showResultToStudent ?? false,
    showCorrectAnswerToStudent: opts.showCorrectAnswerToStudent ?? false,
    showCorrectOnBoard: opts.showCorrectOnBoard ?? false,
    speedBonusEnabled: opts.speedBonusEnabled ?? false,
    streakBonusEnabled: opts.streakBonusEnabled ?? false,
    showPodiumBetweenQuestions: opts.showPodiumBetweenQuestions ?? false,
    soundEffectsEnabled: opts.soundEffectsEnabled ?? false,
    shuffleQuestions: opts.shuffleQuestions ?? false,
    // Pre-toggle sessions had the second client-side shuffle always on, so
    // legacy/absent reads as `true` to keep current assignments behaving
    // identically after the upgrade.
    shuffleAnswerOptions: opts.shuffleAnswerOptions ?? true,
    // Legacy assignments have no attemptLimit — preserve "unlimited" for
    // those rather than retroactively capping ongoing sessions.
    attemptLimit: a.attemptLimit ?? null,
    plcMode: !!a.plc,
    teacherName: a.teacherName ?? defaultTeacherName ?? '',
    selectedPeriodNames: a.periodNames ?? (a.periodName ? [a.periodName] : []),
    plcSheetUrl: a.plc?.sheetUrl ?? '',
  };
}

export const QuizAssignmentSettingsModal: React.FC<
  QuizAssignmentSettingsModalProps
> = ({ assignment, rosters, onClose, onSave, defaultTeacherName }) => {
  // Mode is only editable when the assignment is inactive — changing it
  // mid-session would leave the live session in an incoherent state.
  const modeLocked = assignment.status !== 'inactive';

  const [options, setOptions] = useState<SettingsOptions>(() =>
    initialOptionsFor(assignment, defaultTeacherName)
  );
  const [sessionMode, setSessionMode] = useState<QuizSessionMode>(
    assignment.sessionMode
  );

  // "Auto-Generated PLC Sheet" toggle — defaults ON when:
  //   (a) the linkage was created by the system (`plc.autoGenerated === true`,
  //       set at create time in Widget.tsx and preserved through PLC peer
  //       imports) — this keeps Teacher B's view consistent with Teacher A's
  //       intent and hides the URL field since the system manages it, OR
  //   (b) no URL is attached yet (fresh PLC mode opt-in).
  // Legacy / manually pasted assignments (no `autoGenerated` flag, sheetUrl
  // present) open with the toggle OFF and the URL pre-filled so the user
  // can keep using or edit it. Edit mode never triggers auto-create on
  // save — toggling ON simply hides the field; the existing
  // `assignment.plc.sheetUrl` is preserved by the no-op branch in
  // `handleAssign` when `plcSheetUrl` saves as empty.
  const [useAutoGenerated, setUseAutoGenerated] = useState(
    assignment.plc?.autoGenerated === true || !assignment.plc?.sheetUrl
  );

  const plcSheetUrlInvalid =
    !!options.plcSheetUrl &&
    !options.plcSheetUrl.startsWith('https://docs.google.com/spreadsheets/');

  // Bridge: derive QuizBehaviorSettings from the modal's flattened state so
  // QuizBehaviorSettingsPanel can be driven by the structured shape.
  const behaviorValue = {
    sessionMode,
    sessionOptions: {
      tabWarningsEnabled: options.tabWarningsEnabled,
      showResultToStudent: options.showResultToStudent,
      showCorrectAnswerToStudent: options.showCorrectAnswerToStudent,
      showCorrectOnBoard: options.showCorrectOnBoard,
      speedBonusEnabled: options.speedBonusEnabled,
      streakBonusEnabled: options.streakBonusEnabled,
      showPodiumBetweenQuestions: options.showPodiumBetweenQuestions,
      soundEffectsEnabled: options.soundEffectsEnabled,
      shuffleQuestions: options.shuffleQuestions,
      shuffleAnswerOptions: options.shuffleAnswerOptions,
    } satisfies QuizSessionOptions,
    attemptLimit: options.attemptLimit,
  };

  const handleBehaviorChange = (next: QuizBehaviorSettings) => {
    setSessionMode(next.sessionMode);
    setOptions((p) => ({
      ...p,
      tabWarningsEnabled:
        next.sessionOptions.tabWarningsEnabled ?? p.tabWarningsEnabled,
      showResultToStudent:
        next.sessionOptions.showResultToStudent ?? p.showResultToStudent,
      showCorrectAnswerToStudent:
        next.sessionOptions.showCorrectAnswerToStudent ??
        p.showCorrectAnswerToStudent,
      showCorrectOnBoard:
        next.sessionOptions.showCorrectOnBoard ?? p.showCorrectOnBoard,
      speedBonusEnabled:
        next.sessionOptions.speedBonusEnabled ?? p.speedBonusEnabled,
      streakBonusEnabled:
        next.sessionOptions.streakBonusEnabled ?? p.streakBonusEnabled,
      showPodiumBetweenQuestions:
        next.sessionOptions.showPodiumBetweenQuestions ??
        p.showPodiumBetweenQuestions,
      soundEffectsEnabled:
        next.sessionOptions.soundEffectsEnabled ?? p.soundEffectsEnabled,
      shuffleQuestions:
        next.sessionOptions.shuffleQuestions ?? p.shuffleQuestions,
      shuffleAnswerOptions:
        next.sessionOptions.shuffleAnswerOptions ?? p.shuffleAnswerOptions,
      attemptLimit: next.attemptLimit,
    }));
  };

  const handleAssign = async () => {
    const sessionOptions: QuizSessionOptions = {
      tabWarningsEnabled: options.tabWarningsEnabled,
      showResultToStudent: options.showResultToStudent,
      showCorrectAnswerToStudent: options.showCorrectAnswerToStudent,
      showCorrectOnBoard: options.showCorrectOnBoard,
      speedBonusEnabled: options.speedBonusEnabled,
      streakBonusEnabled: options.streakBonusEnabled,
      showPodiumBetweenQuestions: options.showPodiumBetweenQuestions,
      soundEffectsEnabled: options.soundEffectsEnabled,
      shuffleQuestions: options.shuffleQuestions,
      shuffleAnswerOptions: options.shuffleAnswerOptions,
    };
    // Intentionally pass empty strings (not undefined) so that clearing a
    // field actually writes '' to Firestore. Using `|| undefined` would cause
    // updateDoc to skip the field and leave the previous value in place.
    //
    // PLC linkage rebuild rules: when the toggle is on, carry the current
    // linkage's id/name/memberEmails through and overlay the (possibly
    // edited) sheet URL. When off, write `undefined` to clear the linkage
    // entirely. The current `assignment.plc` is the safe carrier — it was
    // either set at create time (Widget.tsx → createAssignment) or by a
    // prior save through this modal.
    // Only patch `plc` when we have a real existing linkage to overlay onto.
    // Toggling PLC mode on without an `assignment.plc` record would persist
    // a placeholder with empty `id`/`name`, which downstream code treats as
    // a valid PLC linkage — that breaks sharing/membership checks and sheet
    // export. The teacher should re-run assignment-create to acquire a real
    // linkage. (Copilot review on PR #1442.)
    //
    // Empty `trimmedSheetUrl` is a Hide / cancel: the user collapsed the
    // manual-attach disclosure, which clears the form input. We keep the
    // assignment's existing `plc` unchanged rather than overwriting
    // `sheetUrl` with `''` — the empty value would be dropped by the
    // read-side validator on next snapshot and silently lose PLC mode.
    const trimmedSheetUrl = options.plcSheetUrl.trim();
    const plcPatch: QuizAssignmentSettings['plc'] =
      options.plcMode && assignment.plc
        ? trimmedSheetUrl === ''
          ? assignment.plc
          : { ...assignment.plc, sheetUrl: trimmedSheetUrl }
        : undefined;
    const patch: Partial<QuizAssignmentSettings> = {
      className: options.className.trim(),
      sessionMode: modeLocked ? assignment.sessionMode : sessionMode,
      sessionOptions,
      attemptLimit: options.attemptLimit,
      plc: plcPatch,
      teacherName: options.teacherName.trim(),
      periodName: options.selectedPeriodNames[0] ?? '',
      periodNames: options.selectedPeriodNames,
    };
    try {
      await onSave(patch);
      onClose();
    } catch (err) {
      if (import.meta.env.DEV)
        console.error('[QuizAssignmentSettingsModal] save failed:', err);
    }
  };

  return (
    <AssignModal<SettingsOptions>
      isOpen
      onClose={onClose}
      itemTitle={assignment.quizTitle}
      options={options}
      onOptionsChange={setOptions}
      assignmentName={options.className}
      onAssignmentNameChange={(v) =>
        setOptions((prev) => ({ ...prev, className: v }))
      }
      confirmLabel="Save"
      onAssign={handleAssign}
      extraSlot={
        <>
          <div>
            <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
              Class Periods
            </label>
            {rosters.length > 0 ? (
              <div className="space-y-1.5 max-h-36 overflow-y-auto rounded-lg border border-slate-200 bg-white p-2">
                {rosters.map((r) => {
                  const checked = options.selectedPeriodNames.includes(r.name);
                  return (
                    <label
                      key={r.id}
                      className="flex items-center gap-2 cursor-pointer hover:bg-slate-50 rounded px-1.5 py-1"
                    >
                      <input
                        type="checkbox"
                        checked={checked}
                        onChange={() =>
                          setOptions((p) => ({
                            ...p,
                            selectedPeriodNames: checked
                              ? p.selectedPeriodNames.filter(
                                  (n) => n !== r.name
                                )
                              : [...p.selectedPeriodNames, r.name],
                          }))
                        }
                        className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                      />
                      <span className="text-sm text-slate-800">{r.name}</span>
                    </label>
                  );
                })}
              </div>
            ) : (
              <input
                type="text"
                value={options.selectedPeriodNames.join(', ')}
                onChange={(e) => {
                  const names = e.target.value
                    .split(',')
                    .map((n) => n.trim())
                    .filter(Boolean);
                  setOptions((p) => ({
                    ...p,
                    selectedPeriodNames: [...new Set(names)],
                  }));
                }}
                placeholder="e.g. Period 1, Period 2"
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
            )}
            <p className="text-xxs text-slate-400 mt-0.5">
              Select class periods for this assignment. Students will choose
              their class when joining.
            </p>
          </div>

          <QuizBehaviorSettingsPanel
            value={behaviorValue}
            onChange={handleBehaviorChange}
            modeLocked={modeLocked}
          />
        </>
      }
      plcSlot={
        <>
          <div className="border-t border-slate-200/70 pt-3 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Share2 className="w-4 h-4 text-brand-blue-primary" />
              <span className="text-sm font-bold text-brand-blue-dark">
                Share with PLC
              </span>
            </div>
            <Toggle
              checked={options.plcMode}
              onChange={(v) => setOptions((p) => ({ ...p, plcMode: v }))}
              size="sm"
              showLabels={true}
            />
          </div>
          <p className="text-xxs text-slate-500 -mt-1">
            Export results to a shared Google Sheet for your PLC team.
          </p>

          {options.plcMode && (
            <div className="space-y-3 bg-slate-50 rounded-xl p-3 border border-slate-100">
              <div>
                <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
                  Your Name
                </label>
                <input
                  type="text"
                  value={options.teacherName}
                  onChange={(e) =>
                    setOptions((p) => ({ ...p, teacherName: e.target.value }))
                  }
                  placeholder="e.g. Ms. Smith"
                  className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
                <p className="text-xxs text-slate-400 mt-0.5">
                  Appears in the &quot;Teacher&quot; column of the shared sheet
                </p>
              </div>

              <ToggleRow
                label="Auto-Generated PLC Sheet"
                checked={useAutoGenerated}
                onChange={(v) => {
                  setUseAutoGenerated(v);
                  if (v) setOptions((p) => ({ ...p, plcSheetUrl: '' }));
                }}
                hint={
                  useAutoGenerated
                    ? 'Auto-create runs at assignment creation. To rebuild this sheet from scratch later, click "Re-export Sheet" on the Results screen.'
                    : 'Paste a Google Sheet URL — useful for pointing this assignment at a sheet you already have.'
                }
              />
              {!useAutoGenerated && (
                <div>
                  <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
                    Shared Google Sheet URL
                  </label>
                  <input
                    type="text"
                    value={options.plcSheetUrl}
                    onChange={(e) =>
                      setOptions((p) => ({ ...p, plcSheetUrl: e.target.value }))
                    }
                    placeholder="https://docs.google.com/spreadsheets/d/..."
                    className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                  {plcSheetUrlInvalid && (
                    <div className="flex items-center gap-1 mt-1 text-amber-600">
                      <AlertTriangle className="w-3 h-3" />
                      <span className="text-xxs">
                        This doesn&apos;t look like a Google Sheets URL
                      </span>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </>
      }
    />
  );
};
