/**
 * QuizAssignmentSettingsModal — edit the settings for a single assignment.
 *
 * Wave 2-QZ / Task 12 (freeze-live): behavior settings are now READ-ONLY on
 * a launched assignment — they were snapshotted at create time from the quiz.
 * To change behavior, edit the quiz (Settings tab); it affects future
 * assignments only. This modal now shows:
 *   • A read-only behavior summary (formatBehaviorSummary) with an
 *     "Edit in quiz" hint.
 *   • An editable due-date input.
 *   • Editable targeting/sharing fields: class name, periods, PLC, teacher name.
 * The save patch no longer includes sessionMode / sessionOptions / attemptLimit.
 */

import React, { useState } from 'react';
import { AlertTriangle, Share2 } from 'lucide-react';
import type {
  QuizAssignment,
  QuizAssignmentSettings,
  ClassRoster,
} from '@/types';
import { Toggle } from '@/components/common/Toggle';
import { AssignModal, ToggleRow } from '@/components/common/library';
import { formatBehaviorSummary } from '@/utils/quizBehavior';

interface QuizAssignmentSettingsModalProps {
  assignment: QuizAssignment;
  rosters: ClassRoster[];
  onClose: () => void;
  onSave: (patch: Partial<QuizAssignmentSettings>) => Promise<void> | void;
  /**
   * Signed-in teacher's display name. Used as the auto-fill default for the
   * "Your Name" / `teacherName` field when the assignment itself doesn't
   * carry one — applies to fresh assignments and to imports of shared PLC
   * assignments (the importer's row of the shared sheet should be labelled
   * with their own name, not the originator's).
   */
  defaultTeacherName?: string;
}

/** Options object driven through AssignModal's `options` generic. */
interface SettingsOptions {
  className: string;
  plcMode: boolean;
  teacherName: string;
  selectedPeriodNames: string[];
  plcSheetUrl: string;
  /** epoch ms, or null for no due date */
  dueAt: number | null;
}

function initialOptionsFor(
  a: QuizAssignment,
  defaultTeacherName?: string
): SettingsOptions {
  return {
    className: a.className ?? '',
    plcMode: !!a.plc,
    teacherName: a.teacherName ?? defaultTeacherName ?? '',
    selectedPeriodNames: a.periodNames ?? (a.periodName ? [a.periodName] : []),
    plcSheetUrl: a.plc?.sheetUrl ?? '',
    dueAt: a.dueAt ?? null,
  };
}

/** Convert epoch ms → 'YYYY-MM-DD' for a date input value. */
function epochToDateInputValue(epoch: number | null): string {
  if (!epoch) return '';
  return new Date(epoch).toISOString().slice(0, 10);
}

export const QuizAssignmentSettingsModal: React.FC<
  QuizAssignmentSettingsModalProps
> = ({ assignment, rosters, onClose, onSave, defaultTeacherName }) => {
  const [options, setOptions] = useState<SettingsOptions>(() =>
    initialOptionsFor(assignment, defaultTeacherName)
  );

  // "Auto-Generated PLC Sheet" toggle — defaults ON when:
  //   (a) the linkage was created by the system (`plc.autoGenerated === true`,
  //       set at create time in Widget.tsx and preserved through PLC peer
  //       imports) — this keeps Teacher B's view consistent with Teacher A's
  //       intent and hides the URL field since the system manages it, OR
  //   (b) no URL is attached yet (fresh PLC mode opt-in).
  // Legacy / manually pasted assignments (no `autoGenerated` flag, sheetUrl
  // present) open with the toggle OFF and the URL pre-filled so the user
  // can keep using or edit it. Edit mode never triggers auto-create on
  // save — toggling ON simply hides the field; the existing
  // `assignment.plc.sheetUrl` is preserved by the no-op branch in
  // `handleAssign` when `plcSheetUrl` saves as empty.
  const [useAutoGenerated, setUseAutoGenerated] = useState(
    assignment.plc?.autoGenerated === true || !assignment.plc?.sheetUrl
  );

  const plcSheetUrlInvalid =
    !!options.plcSheetUrl &&
    !options.plcSheetUrl.startsWith('https://docs.google.com/spreadsheets/');

  // Build read-only behavior summary from the assignment's frozen behavior.
  const behaviorSummary = formatBehaviorSummary({
    sessionMode: assignment.sessionMode,
    sessionOptions: assignment.sessionOptions ?? {},
    attemptLimit: assignment.attemptLimit ?? null,
  });

  const handleAssign = async () => {
    // Intentionally pass empty strings (not undefined) so that clearing a
    // field actually writes '' to Firestore. Using `|| undefined` would cause
    // updateDoc to skip the field and leave the previous value in place.
    //
    // PLC linkage rebuild rules: when the toggle is on, carry the current
    // linkage's id/name/memberEmails through and overlay the (possibly
    // edited) sheet URL. When off, write `undefined` to clear the linkage
    // entirely. The current `assignment.plc` is the safe carrier — it was
    // either set at create time (Widget.tsx → createAssignment) or by a
    // prior save through this modal.
    // Only patch `plc` when we have a real existing linkage to overlay onto.
    // Toggling PLC mode on without an `assignment.plc` record would persist
    // a placeholder with empty `id`/`name`, which downstream code treats as
    // a valid PLC linkage — that breaks sharing/membership checks and sheet
    // export. The teacher should re-run assignment-create to acquire a real
    // linkage. (Copilot review on PR #1442.)
    //
    // Empty `trimmedSheetUrl` is a Hide / cancel: the user collapsed the
    // manual-attach disclosure, which clears the form input. We keep the
    // assignment's existing `plc` unchanged rather than overwriting
    // `sheetUrl` with `''` — the empty value would be dropped by the
    // read-side validator on next snapshot and silently lose PLC mode.
    const trimmedSheetUrl = options.plcSheetUrl.trim();
    const plcPatch: QuizAssignmentSettings['plc'] =
      options.plcMode && assignment.plc
        ? trimmedSheetUrl === ''
          ? assignment.plc
          : { ...assignment.plc, sheetUrl: trimmedSheetUrl }
        : undefined;

    // Freeze-live: behavior fields (sessionMode, sessionOptions, attemptLimit)
    // are intentionally OMITTED from the patch. They were frozen at create
    // time and must only change by editing the source quiz (affects future
    // assignments). Omitting them means Firestore leaves those fields untouched.
    const patch: Partial<QuizAssignmentSettings> = {
      className: options.className.trim(),
      plc: plcPatch,
      teacherName: options.teacherName.trim(),
      periodName: options.selectedPeriodNames[0] ?? '',
      periodNames: options.selectedPeriodNames,
      dueAt: options.dueAt,
    };
    try {
      await onSave(patch);
      onClose();
    } catch (err) {
      if (import.meta.env.DEV)
        console.error('[QuizAssignmentSettingsModal] save failed:', err);
    }
  };

  return (
    <AssignModal<SettingsOptions>
      isOpen
      onClose={onClose}
      itemTitle={assignment.quizTitle}
      options={options}
      onOptionsChange={setOptions}
      assignmentName={options.className}
      onAssignmentNameChange={(v) =>
        setOptions((prev) => ({ ...prev, className: v }))
      }
      confirmLabel="Save"
      onAssign={handleAssign}
      extraSlot={
        <>
          <div>
            <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
              Class Periods
            </label>
            {rosters.length > 0 ? (
              <div className="space-y-1.5 max-h-36 overflow-y-auto rounded-lg border border-slate-200 bg-white p-2">
                {rosters.map((r) => {
                  const checked = options.selectedPeriodNames.includes(r.name);
                  return (
                    <label
                      key={r.id}
                      className="flex items-center gap-2 cursor-pointer hover:bg-slate-50 rounded px-1.5 py-1"
                    >
                      <input
                        type="checkbox"
                        checked={checked}
                        onChange={() =>
                          setOptions((p) => ({
                            ...p,
                            selectedPeriodNames: checked
                              ? p.selectedPeriodNames.filter(
                                  (n) => n !== r.name
                                )
                              : [...p.selectedPeriodNames, r.name],
                          }))
                        }
                        className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                      />
                      <span className="text-sm text-slate-800">{r.name}</span>
                    </label>
                  );
                })}
              </div>
            ) : (
              <input
                type="text"
                value={options.selectedPeriodNames.join(', ')}
                onChange={(e) => {
                  const names = e.target.value
                    .split(',')
                    .map((n) => n.trim())
                    .filter(Boolean);
                  setOptions((p) => ({
                    ...p,
                    selectedPeriodNames: [...new Set(names)],
                  }));
                }}
                placeholder="e.g. Period 1, Period 2"
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
            )}
            <p className="text-xxs text-slate-400 mt-0.5">
              Select class periods for this assignment. Students will choose
              their class when joining.
            </p>
          </div>

          {/* Due date */}
          <div>
            <label
              htmlFor="assignment-settings-due-date"
              className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1"
            >
              Due Date <span className="font-normal">(optional)</span>
            </label>
            <input
              id="assignment-settings-due-date"
              type="date"
              data-testid="assignment-due-date"
              value={epochToDateInputValue(options.dueAt)}
              onChange={(e) => {
                const val = e.target.value;
                setOptions((p) => ({
                  ...p,
                  dueAt: val ? new Date(val).getTime() : null,
                }));
              }}
              className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>

          {/* Read-only behavior summary — freeze-live: behavior is frozen at
              create time. To change it, edit the quiz settings (affects future
              assignments). */}
          <div className="bg-slate-50 rounded-xl p-3 border border-slate-100 space-y-1.5">
            <div className="flex items-center justify-between gap-2">
              <p className="text-xxs font-bold text-slate-400 uppercase tracking-widest">
                Behavior
              </p>
              <span className="text-xxs text-slate-400">
                Edit in the quiz editor
              </span>
            </div>
            <p
              data-testid="assignment-behavior-summary"
              className="text-sm text-slate-600 leading-snug"
            >
              {behaviorSummary}
            </p>
          </div>
        </>
      }
      plcSlot={
        <>
          <div className="border-t border-slate-200/70 pt-3 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Share2 className="w-4 h-4 text-brand-blue-primary" />
              <span className="text-sm font-bold text-brand-blue-dark">
                Share with PLC
              </span>
            </div>
            <Toggle
              checked={options.plcMode}
              onChange={(v) => setOptions((p) => ({ ...p, plcMode: v }))}
              size="sm"
              showLabels={true}
            />
          </div>
          <p className="text-xxs text-slate-500 -mt-1">
            Export results to a shared Google Sheet for your PLC team.
          </p>

          {options.plcMode && (
            <div className="space-y-3 bg-slate-50 rounded-xl p-3 border border-slate-100">
              <div>
                <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
                  Your Name
                </label>
                <input
                  type="text"
                  value={options.teacherName}
                  onChange={(e) =>
                    setOptions((p) => ({ ...p, teacherName: e.target.value }))
                  }
                  placeholder="e.g. Ms. Smith"
                  className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
                <p className="text-xxs text-slate-400 mt-0.5">
                  Appears in the &quot;Teacher&quot; column of the shared sheet
                </p>
              </div>

              <ToggleRow
                label="Auto-Generated PLC Sheet"
                checked={useAutoGenerated}
                onChange={(v) => {
                  setUseAutoGenerated(v);
                  if (v) setOptions((p) => ({ ...p, plcSheetUrl: '' }));
                }}
                hint={
                  useAutoGenerated
                    ? 'Auto-create runs at assignment creation. To rebuild this sheet from scratch later, click "Re-export Sheet" on the Results screen.'
                    : 'Paste a Google Sheet URL — useful for pointing this assignment at a sheet you already have.'
                }
              />
              {!useAutoGenerated && (
                <div>
                  <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
                    Shared Google Sheet URL
                  </label>
                  <input
                    type="text"
                    value={options.plcSheetUrl}
                    onChange={(e) =>
                      setOptions((p) => ({ ...p, plcSheetUrl: e.target.value }))
                    }
                    placeholder="https://docs.google.com/spreadsheets/d/..."
                    className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                  {plcSheetUrlInvalid && (
                    <div className="flex items-center gap-1 mt-1 text-amber-600">
                      <AlertTriangle className="w-3 h-3" />
                      <span className="text-xxs">
                        This doesn&apos;t look like a Google Sheets URL
                      </span>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </>
      }
    />
  );
};
