// Keep in sync with GEMINI_SPECIFIC_FEATURES in functions/src/adminAnalyticsCompute.ts.
export const AI_FEATURE_LABELS: Record<string, string> = {
  'smart-poll': 'Smart Poll',
  'embed-mini-app': 'Mini App',
  'video-activity-audio-transcription': 'Video Activity',
  quiz: 'Quiz Generation',
  ocr: 'OCR',
  'blooms-ai': "Bloom's AI",
  'video-activity-recommend': 'Video Recommendations',
  'dashboard-layout': 'Dashboard Layout AI',
  'instructional-routine': 'Instructional Routines AI',
  'widget-builder': 'Widget Builder AI',
  'widget-explainer': 'Widget Explainer AI',
  tts: 'Quiz Read-Aloud',
  translation: 'Quiz Translation',
  'paper-handwritten-responses': 'Handwritten Answers (pages)',
  'video-activity-ai': 'Video Activity AI',
  'guided-learning-ai': 'Guided Learning AI',
  'mini-app-ai': 'Mini App AI',
  'drawing-ai': 'Drawing Text Recognition',
  'webcam-ai': 'Webcam Text Recognition',
};
