import { Z_INDEX } from './config/zIndex';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './components/**/*.{js,ts,jsx,tsx}',
    './context/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
    './*.{js,ts,jsx,tsx}',
    './config/**/*.ts',
  ],
  safelist: [
    // Dynamic font classes used by Clock and TimeTool widgets via font-${globalStyle.fontFamily}
    {
      pattern:
        /^font-(sans|mono|handwritten|rounded|fun|comic|slab|retro|marker|cursive)$/,
    },
    'bg-blue-500',
    'bg-red-500',
    'bg-amber-500',
    'bg-yellow-400',
    'bg-green-500',
    'bg-indigo-500',
    'bg-purple-500',
    'bg-pink-500',
    'bg-cyan-500',
    'bg-slate-700',
    'bg-sky-600',
    'bg-orange-500',
    'bg-gray-800',
    'bg-yellow-600',
    'bg-emerald-600',
    'bg-sky-400',
    'bg-teal-600',
    'bg-rose-500',
    'bg-orange-600',
    'bg-indigo-600',
    'bg-violet-600',
    // Background customization classes
    'bg-brand-gray-darkest',
    'bg-brand-blue-dark',
    'bg-emerald-950',
    'bg-brand-red-dark',
    'bg-brand-gray-lightest',
    'bg-white',
    'bg-[radial-gradient(#e5e7eb_1px,transparent_1px)]',
    '[background-size:16px_16px]',
    'bg-slate-100',
    'bg-gradient-to-br',
    'from-slate-900',
    'to-slate-700',
    'from-brand-blue-primary',
    'to-brand-blue-dark',
    'from-emerald-400',
    'to-cyan-500',
    'from-rose-400',
    'to-orange-400',
  ],
  theme: {
    extend: {
      zIndex: {
        base: Z_INDEX.base.toString(),
        decorator: Z_INDEX.decorator.toString(),
        content: Z_INDEX.content.toString(),
        controls: Z_INDEX.controls.toString(),
        widget: Z_INDEX.widget.toString(),
        'widget-drag': Z_INDEX.widgetDrag.toString(),
        maximized: Z_INDEX.maximized.toString(),
        dock: Z_INDEX.dock.toString(),
        'dock-dragging': Z_INDEX.dockDragging.toString(),
        sidebar: Z_INDEX.sidebar.toString(),
        header: Z_INDEX.header.toString(),
        backdrop: Z_INDEX.backdrop.toString(),
        'confirm-overlay': Z_INDEX.confirmOverlay.toString(),
        modal: Z_INDEX.modal.toString(),
        'modal-content': Z_INDEX.modalContent.toString(),
        popover: Z_INDEX.popover.toString(),
        'tool-menu': Z_INDEX.toolMenu.toString(),
        tooltip: Z_INDEX.tooltip.toString(),
        toast: Z_INDEX.toast.toString(),
        critical: Z_INDEX.critical.toString(),
        cursor: Z_INDEX.cursor.toString(),
        'sticker-control': Z_INDEX.stickerControl.toString(),
        'widget-resize': Z_INDEX.widgetResize.toString(),
        'widget-internal-overlay': Z_INDEX.widgetInternalOverlay.toString(),
        dropdown: Z_INDEX.dropdown.toString(),
        overlay: Z_INDEX.overlay.toString(),
        'modal-nested': Z_INDEX.modalNested.toString(),
        'modal-nested-content': Z_INDEX.modalNestedContent.toString(),
        'modal-deep': Z_INDEX.modalDeep.toString(),
        'modal-deep-content': Z_INDEX.modalDeepContent.toString(),
      },
      fontFamily: {
        sans: ['"Lexend"', 'sans-serif'],
        serif: ['"Merriweather"', 'serif'],
        mono: ['"Roboto Mono"', 'monospace'],
        handwritten: ['"Patrick Hand"', 'cursive'],
        rounded: ['"Varela Round"', 'sans-serif'],
        fun: ['"Fredoka"', 'sans-serif'],
        comic: ['"Comic Neue"', 'cursive'],
        slab: ['"Roboto Slab"', 'serif'],
        retro: ['"VT323"', 'monospace'],
        marker: ['"Permanent Marker"', 'cursive'],
        cursive: ['"Dancing Script"', 'cursive'],
      },
      fontSize: {
        xxs: ['10px', '14px'], // Micro-typography token
        xxxs: ['8px', '10px'], // Micro-typography token
      },
      colors: {
        brand: {
          blue: {
            primary: '#2d3f89',
            dark: '#1d2a5d',
            light: '#4356a0',
            lighter: '#eaecf5',
          },
          red: {
            primary: '#ad2122',
            dark: '#7a1718',
            light: '#c13435',
            lighter: '#e5c7c7',
          },
          gray: {
            darkest: '#1a1a1a',
            dark: '#333333',
            primary: '#666666',
            light: '#999999',
            lighter: '#cccccc',
            lightest: '#f3f3f3',
          },
        },
      },
      keyframes: {
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        jiggle: {
          '0%, 100%': { transform: 'rotate(-1deg)' },
          '50%': { transform: 'rotate(1deg)' },
        },
      },
      animation: {
        'spin-slow': 'spin-slow 12s linear infinite',
        jiggle: 'jiggle 0.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
