import { Z_INDEX } from './config/zIndex';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './components/**/*.{js,ts,jsx,tsx}',
    './context/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
    './*.{js,ts,jsx,tsx}',
    './config/**/*.ts',
  ],
  safelist: [
    // Dynamic font classes used by Clock and TimeTool widgets via font-${globalStyle.fontFamily}
    {
      pattern:
        /^font-(sans|serif|mono|handwritten|rounded|fun|comic|slab|retro|marker|cursive)$/,
    },
    'bg-blue-500',
    'bg-red-500',
    'bg-amber-500',
    'bg-yellow-400',
    'bg-green-500',
    'bg-indigo-500',
    'bg-purple-500',
    'bg-pink-500',
    'bg-cyan-500',
    'bg-slate-700',
    'bg-sky-600',
    'bg-orange-500',
    'bg-gray-800',
    'bg-yellow-600',
    'bg-emerald-600',
    'bg-sky-400',
    'bg-teal-600',
    'bg-rose-500',
    'bg-orange-600',
    'bg-indigo-600',
    'bg-violet-600',
    // Background solid color classes
    'bg-brand-gray-darkest',
    'bg-brand-blue-dark',
    'bg-emerald-950',
    'bg-brand-red-dark',
    'bg-sky-900',
    'bg-purple-950',
    'bg-amber-900',
    'bg-stone-800',
    'bg-slate-600',
    'bg-lime-900',
    'bg-pink-900',
    'bg-brand-gray-lightest',
    'bg-white',
    'bg-slate-400',
    // Background pattern classes
    'bg-[radial-gradient(#e5e7eb_1px,transparent_1px)]',
    '[background-size:16px_16px]',
    'bg-slate-100',
    'bg-[radial-gradient(#94a3b8_2px,transparent_2px)]',
    '[background-size:24px_24px]',
    'bg-[repeating-linear-gradient(0deg,#e5e7eb,#e5e7eb_1px,transparent_1px,transparent_24px)]',
    'bg-[repeating-linear-gradient(0deg,#cbd5e1,#cbd5e1_1px,transparent_1px,transparent_24px),repeating-linear-gradient(90deg,#cbd5e1,#cbd5e1_1px,transparent_1px,transparent_24px)]',
    'bg-[repeating-linear-gradient(0deg,#93c5fd_0_1px,transparent_1px_28px),linear-gradient(90deg,#fca5a5_0_1px,transparent_1px_100%)]',
    '[background-size:100%_28px,100%_100%]',
    '[background-position:0_40px,32px_0]',
    'bg-[#fffef5]',
    'bg-[repeating-linear-gradient(45deg,#e2e8f0,#e2e8f0_1px,transparent_1px,transparent_12px)]',
    'bg-[repeating-linear-gradient(0deg,#475569,#475569_1px,transparent_1px,transparent_20px),repeating-linear-gradient(90deg,#475569,#475569_1px,transparent_1px,transparent_20px)]',
    'bg-slate-700',
    'bg-[repeating-linear-gradient(0deg,rgba(255,255,255,0.05),rgba(255,255,255,0.05)_1px,transparent_1px,transparent_20px),repeating-linear-gradient(90deg,rgba(255,255,255,0.05),rgba(255,255,255,0.05)_1px,transparent_1px,transparent_20px)]',
    'bg-[#2d5016]',
    'bg-[repeating-linear-gradient(0deg,#e2e8f0,#e2e8f0_1px,transparent_1px,transparent_40px),repeating-linear-gradient(90deg,#e2e8f0,#e2e8f0_1px,transparent_1px,transparent_40px)]',
    'bg-[#f8fafc]',
    'bg-[repeating-linear-gradient(0deg,rgba(96,165,250,0.3),rgba(96,165,250,0.3)_1px,transparent_1px,transparent_20px),repeating-linear-gradient(90deg,rgba(96,165,250,0.3),rgba(96,165,250,0.3)_1px,transparent_1px,transparent_20px)]',
    'bg-[#1e3a5f]',
    // Background gradient classes
    'bg-gradient-to-br',
    'from-slate-900',
    'to-slate-700',
    'from-brand-blue-primary',
    'to-brand-blue-dark',
    'from-emerald-400',
    'to-cyan-500',
    'from-rose-400',
    'to-orange-400',
    'from-blue-600',
    'via-cyan-500',
    'to-teal-400',
    'from-green-800',
    'via-emerald-600',
    'to-lime-500',
    'from-purple-500',
    'via-violet-400',
    'to-indigo-300',
    'from-pink-400',
    'via-fuchsia-400',
    'to-purple-500',
    'from-amber-700',
    'via-orange-600',
    'to-yellow-500',
    'from-indigo-950',
    'via-blue-900',
    'to-violet-900',
    'from-green-300',
    'via-yellow-200',
    'to-pink-300',
    'from-emerald-950',
    'via-green-900',
    'to-slate-800',
  ],
  theme: {
    extend: {
      zIndex: {
        base: Z_INDEX.base.toString(),
        decorator: Z_INDEX.decorator.toString(),
        content: Z_INDEX.content.toString(),
        controls: Z_INDEX.controls.toString(),
        'item-dragging': Z_INDEX.itemDragging.toString(),
        widget: Z_INDEX.widget.toString(),
        'widget-drag': Z_INDEX.widgetDrag.toString(),
        maximized: Z_INDEX.maximized.toString(),
        dock: Z_INDEX.dock.toString(),
        'dock-dragging': Z_INDEX.dockDragging.toString(),
        sidebar: Z_INDEX.sidebar.toString(),
        header: Z_INDEX.header.toString(),
        backdrop: Z_INDEX.backdrop.toString(),
        'announcement-overlay': Z_INDEX.announcementOverlay.toString(),
        'announcement-maximized': Z_INDEX.announcementMaximized.toString(),
        'confirm-overlay': Z_INDEX.confirmOverlay.toString(),
        'snap-preview': Z_INDEX.snapPreview.toString(),
        'system-banner': Z_INDEX.systemBanner.toString(),
        modal: Z_INDEX.modal.toString(),
        'modal-content': Z_INDEX.modalContent.toString(),
        popover: Z_INDEX.popover.toString(),
        'tool-menu': Z_INDEX.toolMenu.toString(),
        tooltip: Z_INDEX.tooltip.toString(),
        toast: Z_INDEX.toast.toString(),
        dialog: Z_INDEX.dialog.toString(),
        critical: Z_INDEX.critical.toString(),
        cursor: Z_INDEX.cursor.toString(),
        'sticker-control': Z_INDEX.stickerControl.toString(),
        'widget-resize': Z_INDEX.widgetResize.toString(),
        'widget-internal-overlay': Z_INDEX.widgetInternalOverlay.toString(),
        'widget-control': Z_INDEX.widgetControl.toString(),
        dropdown: Z_INDEX.dropdown.toString(),
        overlay: Z_INDEX.overlay.toString(),
        'modal-nested': Z_INDEX.modalNested.toString(),
        'modal-nested-content': Z_INDEX.modalNestedContent.toString(),
        'modal-deep': Z_INDEX.modalDeep.toString(),
        'modal-deep-content': Z_INDEX.modalDeepContent.toString(),
      },
      fontFamily: {
        sans: ['"Lexend"', 'sans-serif'],
        serif: ['"Merriweather"', 'serif'],
        mono: ['"Roboto Mono"', 'monospace'],
        handwritten: ['"Patrick Hand"', 'cursive'],
        rounded: ['"Varela Round"', 'sans-serif'],
        fun: ['"Fredoka"', 'sans-serif'],
        comic: ['"Comic Neue"', 'cursive'],
        slab: ['"Roboto Slab"', 'serif'],
        retro: ['"VT323"', 'monospace'],
        marker: ['"Permanent Marker"', 'cursive'],
        cursive: ['"Dancing Script"', 'cursive'],
      },
      fontSize: {
        xxs: ['10px', '14px'], // Micro-typography token
        xxxs: ['8px', '10px'], // Micro-typography token
      },
      colors: {
        brand: {
          blue: {
            primary: '#2d3f89',
            dark: '#1d2a5d',
            light: '#4356a0',
            lighter: '#eaecf5',
          },
          red: {
            primary: '#ad2122',
            dark: '#7a1718',
            light: '#c13435',
            lighter: '#e5c7c7',
          },
          gray: {
            darkest: '#1a1a1a',
            dark: '#333333',
            primary: '#666666',
            light: '#999999',
            lighter: '#cccccc',
            lightest: '#f3f3f3',
          },
        },
      },
      keyframes: {
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        jiggle: {
          '0%, 100%': { transform: 'rotate(-1deg)' },
          '50%': { transform: 'rotate(1deg)' },
        },
        shimmer: {
          '100%': { transform: 'translateX(100%)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        'spin-slow': 'spin-slow 12s linear infinite',
        jiggle: 'jiggle 0.5s ease-in-out infinite',
        shimmer: 'shimmer 1.5s infinite',
        marquee: 'marquee 12s linear infinite',
      },
    },
  },
  plugins: [],
};
