import fs from 'fs';
import path from 'path';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

// Read the build version generated by scripts/generate-version.js so it can be
// inlined into the JS bundle.  This removes the fragile initial network fetch
// that was required to establish the "current" version at runtime.
let __APP_VERSION__ = 'dev';
let __APP_BUILD_ID__ = 'dev';
try {
  const raw = fs.readFileSync(
    path.resolve(__dirname, 'public/version.json'),
    'utf-8'
  );
  const parsed = JSON.parse(raw);
  __APP_VERSION__ = parsed.version;
  // Older version.json files predate buildId; fall back so the compare still works.
  __APP_BUILD_ID__ = parsed.buildId ?? parsed.version;
} catch {
  // version.json hasn't been generated yet (fresh checkout) – fall back to 'dev'
}

// pdf.js decodes CCITT/JBIG2/JPX scans in wasm it fetches from `wasmUrl`, so
// serve its wasm directory in dev and emit it into the build under one path.
const PDFJS_WASM_DIR = path.resolve(__dirname, 'node_modules/pdfjs-dist/wasm');
const PDFJS_WASM_FILES = [
  'jbig2.wasm',
  'jbig2_nowasm_fallback.js',
  'openjpeg.wasm',
  'openjpeg_nowasm_fallback.js',
  'qcms_bg.wasm',
];
const pdfjsWasmPlugin = (): Plugin => ({
  name: 'pdfjs-wasm',
  configureServer(server) {
    server.middlewares.use('/pdfjs-wasm', (req, res, next) => {
      const name = (req.url ?? '').replace(/^\/+/, '').split('?')[0];
      if (!PDFJS_WASM_FILES.includes(name)) return next();
      res.setHeader(
        'Content-Type',
        name.endsWith('.wasm') ? 'application/wasm' : 'text/javascript'
      );
      fs.createReadStream(path.join(PDFJS_WASM_DIR, name)).pipe(res);
    });
  },
  generateBundle() {
    for (const name of PDFJS_WASM_FILES) {
      this.emitFile({
        type: 'asset',
        fileName: `pdfjs-wasm/${name}`,
        source: fs.readFileSync(path.join(PDFJS_WASM_DIR, name)),
      });
    }
  },
});

// App imports of 'firebase/firestore' get the View as write guard (docs/plans/ADMIN_VIEW_AS.md D13).
const FIRESTORE_GUARD = path.resolve(
  __dirname,
  'utils/firestoreViewAsGuard.ts'
);
const firestoreViewAsGuardPlugin = (): Plugin => ({
  name: 'firestore-view-as-guard',
  enforce: 'pre',
  resolveId(source, importer) {
    if (source !== 'firebase/firestore' || !importer) return null;
    const from = importer.split(String.fromCharCode(92)).join('/');
    if (from.includes('/node_modules/')) return null;
    if (path.resolve(importer.split('?')[0]) === FIRESTORE_GUARD) return null;
    return FIRESTORE_GUARD;
  },
});

const commonServerConfig = {
  port: 3000,
  host: '0.0.0.0',
};

export default defineConfig({
  server: {
    ...commonServerConfig,
    // Agent worktrees live inside the repo; watching them stalls the dev server.
    watch: {
      ignored: (p: string) =>
        p
          .split(String.fromCharCode(92))
          .join('/')
          .includes('/.claude/worktrees/'),
    },
  },
  preview: commonServerConfig,
  plugins: [
    ...(process.env.VITEST ? [] : [firestoreViewAsGuardPlugin()]),
    react(),
    pdfjsWasmPlugin(),
  ],
  define: {
    __APP_VERSION__: JSON.stringify(__APP_VERSION__),
    __APP_BUILD_ID__: JSON.stringify(__APP_BUILD_ID__),
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '.'),
      // The widget grader's build keeps React Profiler callbacks (R3 in docs/plans/WIDGET_RUBRIC.md).
      ...(process.env.GRADER_PROFILE
        ? { 'react-dom/client': 'react-dom/profiling' }
        : {}),
    },
  },
  build: {
    // Keep the global chunk size warning at 500 kB so we don't hide regressions in other chunks.
    // Warnings for inherently large WASM-heavy chunks like @imgly/background-removal and ort-wasm
    // are expected and accepted rather than suppressed globally.
    chunkSizeWarningLimit: 500,
    rollupOptions: {
      output: {
        manualChunks(id: string) {
          if (!id.includes('node_modules')) return undefined;
          if (/[\\/]node_modules[\\/](react|react-dom)[\\/]/.test(id)) {
            return 'react-vendor';
          }
          const firebase = id.match(
            /[\\/]node_modules[\\/]firebase[\\/](app|auth|firestore|storage|functions)[\\/]/
          );
          if (firebase) return `firebase-${firebase[1]}`;
          if (/[\\/]node_modules[\\/]@dnd-kit[\\/]/.test(id)) return 'dnd-kit';
          if (
            /[\\/]node_modules[\\/]@imgly[\\/]background-removal[\\/]/.test(id)
          ) {
            return 'imgly-bg-removal';
          }
          if (/[\\/]node_modules[\\/](html-to-image|jszip)[\\/]/.test(id))
            return 'utils';
          return undefined;
        },
      },
    },
  },
});
