import fs from 'fs';
import path from 'path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// Read the build version generated by scripts/generate-version.js so it can be
// inlined into the JS bundle.  This removes the fragile initial network fetch
// that was required to establish the "current" version at runtime.
let __APP_VERSION__ = 'dev';
try {
  const raw = fs.readFileSync(
    path.resolve(__dirname, 'public/version.json'),
    'utf-8'
  );
  __APP_VERSION__ = JSON.parse(raw).version;
} catch {
  // version.json hasn't been generated yet (fresh checkout) – fall back to 'dev'
}

const commonServerConfig = {
  port: 3000,
  host: '0.0.0.0',
};

export default defineConfig({
  server: commonServerConfig,
  preview: commonServerConfig,
  plugins: [react()],
  define: {
    __APP_VERSION__: JSON.stringify(__APP_VERSION__),
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '.'),
    },
  },
  build: {
    // Keep the global chunk size warning at 500 kB so we don't hide regressions in other chunks.
    // Warnings for inherently large WASM-heavy chunks like @imgly/background-removal and ort-wasm
    // are expected and accepted rather than suppressed globally.
    chunkSizeWarningLimit: 500,
    rollupOptions: {
      output: {
        manualChunks: {
          'react-vendor': ['react', 'react-dom'],
          'firebase-app': ['firebase/app'],
          'firebase-auth': ['firebase/auth'],
          'firebase-firestore': ['firebase/firestore'],
          'firebase-storage': ['firebase/storage'],
          'firebase-functions': ['firebase/functions'],
          'dnd-kit': [
            '@dnd-kit/core',
            '@dnd-kit/sortable',
            '@dnd-kit/utilities',
          ],
          'imgly-bg-removal': ['@imgly/background-removal'],
          utils: ['html-to-image', 'jszip'],
        },
      },
    },
  },
});
