import type { LucideIcon } from 'lucide-react';
import {
  Anchor,
  Apple,
  Atom,
  Backpack,
  Banana,
  Bell,
  Bike,
  Bird,
  Blocks,
  Bone,
  Book,
  BookOpen,
  Bot,
  Bug,
  Bus,
  Cake,
  Candy,
  Car,
  Carrot,
  Castle,
  Cat,
  Cherry,
  Circle,
  Citrus,
  Cloud,
  CloudSun,
  Clover,
  Compass,
  Cookie,
  Croissant,
  Crown,
  Diamond,
  Dice5,
  Dog,
  Donut,
  Drum,
  Earth,
  Egg,
  Feather,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Goal,
  Grape,
  Guitar,
  Hand,
  Heart,
  Hexagon,
  House,
  IceCreamCone,
  Key,
  Leaf,
  Lightbulb,
  Lollipop,
  Magnet,
  Map as MapIcon,
  Medal,
  Microscope,
  Moon,
  Mountain,
  Music,
  Octagon,
  Origami,
  Palette,
  Paintbrush,
  PartyPopper,
  PawPrint,
  Pencil,
  Pentagon,
  Piano,
  Pizza,
  Plane,
  Popcorn,
  Puzzle,
  Rabbit,
  Rainbow,
  Rocket,
  Sailboat,
  Sandwich,
  Shell,
  Ship,
  Smile,
  Snail,
  Snowflake,
  Sparkles,
  Sprout,
  Square,
  Squirrel,
  Star,
  Sun,
  Telescope,
  Tent,
  ThumbsUp,
  Tractor,
  TrainFront,
  TreeDeciduous,
  TreePine,
  Triangle,
  Trophy,
  Truck,
  Turtle,
  Umbrella,
  Volleyball,
  Waves,
  Wind,
  Worm,
  Zap,
} from 'lucide-react';

export interface GroupIcon {
  id: string;
  Icon: LucideIcon;
  /** Search words; the id is matched too. */
  keywords: string;
}

const icon = (id: string, Icon: LucideIcon, keywords = ''): GroupIcon => ({
  id,
  Icon,
  keywords: `${id.replace(/-/g, ' ')} ${keywords}`,
});

/** Kid-friendly symbols for class groups, roughly by theme. */
export const GROUP_ICONS: GroupIcon[] = [
  icon('star', Star, 'shape night sky'),
  icon('heart', Heart, 'shape love'),
  icon('circle', Circle, 'shape round'),
  icon('square', Square, 'shape box'),
  icon('triangle', Triangle, 'shape'),
  icon('diamond', Diamond, 'shape'),
  icon('hexagon', Hexagon, 'shape honeycomb'),
  icon('pentagon', Pentagon, 'shape'),
  icon('octagon', Octagon, 'shape stop'),
  icon('sparkles', Sparkles, 'shine magic stars'),
  icon('sun', Sun, 'weather sunny day'),
  icon('moon', Moon, 'night sky'),
  icon('cloud', Cloud, 'weather sky'),
  icon('cloud-sun', CloudSun, 'weather partly'),
  icon('rainbow', Rainbow, 'weather colors'),
  icon('snowflake', Snowflake, 'winter snow cold'),
  icon('umbrella', Umbrella, 'rain weather'),
  icon('zap', Zap, 'lightning bolt thunder'),
  icon('flame', Flame, 'fire hot'),
  icon('wind', Wind, 'weather breeze'),
  icon('waves', Waves, 'ocean sea water'),
  icon('mountain', Mountain, 'nature hill'),
  icon('earth', Earth, 'world globe planet'),
  icon('flower', Flower, 'nature plant garden'),
  icon('daisy', Flower2, 'flower nature plant'),
  icon('leaf', Leaf, 'nature plant tree'),
  icon('sprout', Sprout, 'plant grow seed'),
  icon('pine-tree', TreePine, 'nature forest evergreen'),
  icon('tree', TreeDeciduous, 'nature forest'),
  icon('clover', Clover, 'lucky shamrock plant'),
  icon('cat', Cat, 'animal pet kitten'),
  icon('dog', Dog, 'animal pet puppy'),
  icon('rabbit', Rabbit, 'animal bunny pet'),
  icon('turtle', Turtle, 'animal slow reptile'),
  icon('fish', Fish, 'animal ocean sea pet'),
  icon('bird', Bird, 'animal fly'),
  icon('squirrel', Squirrel, 'animal'),
  icon('snail', Snail, 'animal slow'),
  icon('bug', Bug, 'animal insect beetle'),
  icon('worm', Worm, 'animal'),
  icon('shell', Shell, 'ocean beach sea'),
  icon('paw', PawPrint, 'animal pet footprint'),
  icon('bone', Bone, 'dog'),
  icon('egg', Egg, 'food chick'),
  icon('feather', Feather, 'bird'),
  icon('apple', Apple, 'food fruit'),
  icon('banana', Banana, 'food fruit'),
  icon('cherry', Cherry, 'food fruit'),
  icon('grape', Grape, 'food fruit'),
  icon('orange', Citrus, 'food fruit citrus lemon'),
  icon('carrot', Carrot, 'food vegetable'),
  icon('cookie', Cookie, 'food snack treat'),
  icon('cake', Cake, 'food birthday treat'),
  icon('donut', Donut, 'food treat doughnut'),
  icon('ice-cream', IceCreamCone, 'food treat'),
  icon('lollipop', Lollipop, 'food candy treat'),
  icon('candy', Candy, 'food treat sweet'),
  icon('popcorn', Popcorn, 'food snack movie'),
  icon('pizza', Pizza, 'food'),
  icon('sandwich', Sandwich, 'food lunch'),
  icon('croissant', Croissant, 'food bread'),
  icon('rocket', Rocket, 'space launch'),
  icon('plane', Plane, 'airplane fly travel'),
  icon('car', Car, 'vehicle drive'),
  icon('bus', Bus, 'vehicle school'),
  icon('train', TrainFront, 'vehicle'),
  icon('truck', Truck, 'vehicle'),
  icon('tractor', Tractor, 'vehicle farm'),
  icon('bike', Bike, 'bicycle ride'),
  icon('ship', Ship, 'boat ocean'),
  icon('sailboat', Sailboat, 'boat ocean sea'),
  icon('anchor', Anchor, 'boat ocean sea'),
  icon('soccer', Goal, 'sports ball goal'),
  icon('volleyball', Volleyball, 'sports ball'),
  icon('trophy', Trophy, 'win prize cup'),
  icon('medal', Medal, 'win prize'),
  icon('crown', Crown, 'king queen royal'),
  icon('gem', Gem, 'jewel treasure'),
  icon('gift', Gift, 'present birthday'),
  icon('party', PartyPopper, 'celebrate'),
  icon('music', Music, 'song note'),
  icon('guitar', Guitar, 'music'),
  icon('drum', Drum, 'music'),
  icon('piano', Piano, 'music keyboard'),
  icon('palette', Palette, 'art paint color'),
  icon('paintbrush', Paintbrush, 'art paint'),
  icon('pencil', Pencil, 'write draw school'),
  icon('book', Book, 'read school library'),
  icon('open-book', BookOpen, 'read school library'),
  icon('backpack', Backpack, 'school bag'),
  icon('puzzle', Puzzle, 'game piece'),
  icon('blocks', Blocks, 'build game toy'),
  icon('dice', Dice5, 'game'),
  icon('game', Gamepad2, 'video game controller'),
  icon('origami', Origami, 'paper bird craft'),
  icon('lightbulb', Lightbulb, 'idea think'),
  icon('magnet', Magnet, 'science'),
  icon('atom', Atom, 'science'),
  icon('flask', FlaskConical, 'science lab'),
  icon('microscope', Microscope, 'science lab'),
  icon('telescope', Telescope, 'space science stars'),
  icon('compass', Compass, 'map explore'),
  icon('map', MapIcon, 'explore travel'),
  icon('flag', Flag, 'goal finish'),
  icon('tent', Tent, 'camp outdoors'),
  icon('castle', Castle, 'king queen'),
  icon('house', House, 'home'),
  icon('key', Key, 'lock'),
  icon('bell', Bell, 'ring'),
  icon('glasses', Glasses, 'read'),
  icon('footprints', Footprints, 'walk feet'),
  icon('hand', Hand, 'wave high five'),
  icon('thumbs-up', ThumbsUp, 'good yes'),
  icon('smile', Smile, 'happy face'),
  icon('ghost', Ghost, 'halloween spooky'),
  icon('robot', Bot, 'machine'),
];

const BY_ID = new Map(GROUP_ICONS.map((i) => [i.id, i]));

export const groupIcon = (id: string | undefined): GroupIcon =>
  (id ? BY_ID.get(id) : undefined) ?? GROUP_ICONS[0];

export function searchGroupIcons(query: string): GroupIcon[] {
  const words = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (words.length === 0) return GROUP_ICONS;
  return GROUP_ICONS.filter((i) =>
    words.every((w) => i.keywords.split(' ').some((k) => k.startsWith(w)))
  );
}
