import { RandomGroup, SharedGroup, Station } from '@/types';
import { WIDGET_PALETTE } from '@/config/colors';

/** UUID v4 pattern — used to detect synthetic group IDs generated by crypto.randomUUID(). */
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Convert Randomizer groups into a Stations widget config payload. Used by
 * the "Send Groups → Stations" button on the Randomizer settings panel; lives
 * in its own file so re-exporting it from Settings.tsx doesn't trip the
 * `react-refresh/only-export-components` lint rule.
 *
 * @param groups        The RandomGroup[] from config.lastResult.
 * @param sharedGroups  Optional dashboard.sharedGroups — used to resolve a
 *                      group's UUID id to its human-readable name.  Without
 *                      this, groups created by the random groupmaker (whose
 *                      `id` is a crypto.randomUUID()) would produce station
 *                      titles that are raw UUID strings instead of "Group 1",
 *                      "Group 2", etc.
 */
export const buildStationsFromRandomGroups = (
  groups: RandomGroup[],
  sharedGroups?: SharedGroup[]
): { stations: Station[]; assignments: Record<string, string | null> } => {
  const sharedMap = new Map((sharedGroups ?? []).map((sg) => [sg.id, sg.name]));

  const stations: Station[] = groups.map((group, i) => {
    const rawId = group.id;
    let title: string;
    if (!rawId) {
      title = `Group ${i + 1}`;
    } else if (UUID_RE.test(rawId)) {
      // The id is a synthetic UUID from the groupmaker. Resolve via sharedGroups;
      // fall back to "Group N" if not found (e.g. sharedGroups not passed or pruned).
      const resolved = sharedMap.get(rawId);
      title =
        resolved && resolved.trim().length > 0
          ? resolved.trim()
          : `Group ${i + 1}`;
    } else {
      // Legacy path: id is already a human-readable string (e.g. "Reading Corner").
      const trimmed = rawId.trim();
      title = trimmed.length > 0 ? trimmed : `Group ${i + 1}`;
    }
    return {
      id: crypto.randomUUID(),
      title,
      color: WIDGET_PALETTE[i % WIDGET_PALETTE.length],
      order: i,
    };
  });
  const assignments: Record<string, string | null> = {};
  groups.forEach((group, i) => {
    const station = stations[i];
    for (const name of group.names) {
      // Last write wins for duplicate names across groups — that's the only
      // sane choice given assignments are keyed by display name.
      assignments[name] = station.id;
    }
  });
  return { stations, assignments };
};
