// Mirror of isAdminPreviewFeature in config/featureDefaults.ts; config/featureDefaults.test.ts keeps it in sync.
export const ADMIN_PREVIEW_FEATURES: readonly string[] = [
  'settings-drawer',
  'quiz-read-aloud',
  'quiz-translation',
  'question-bank-ai',
  'question-bank-imscc-import',
  'quiz-imscc-import',
  'quiz-document-ai-reader',
  'quiz-import-suggested-targets',
  'quiz-import-passages',
  'paper-answer-sheets',
  'roster-groups',
  'quiz-document-import',
  'sub-share-collections',
  'gl-player-v2',
  'tab-away-timer',
  'gl-live-tours',
  'gl-studio',
  'per-period-access',
  'quiz-results-print',
  'plc-home-v2',
  'plc-norming-flags',
  'plc-flashcards',
  'quiz-choose-all',
  'quiz-choice-editor',
  'quiz-sections',
  'quiz-fib-alternates',
  'quiz-fib-multi-blank',
  'modal-fullscreen',
  'quiz-results-tools',
  'quiz-grader-v2',
  'gl-callout-editing',
  'plc-notes-rich-editor',
  'paper-handwritten-responses',
  'claude-connector',
  'claude-connector-guided-learning',
  'video-activity-live',
  'quiz-student-view',
  'quiz-score-on-submit',
  'projects-group-view',
  'quiz-per-class-due-dates',
  'gradebook',
  'student-gradebook',
  'quiz-review-split',
  'quiz-time-limit',
  'group-reminders',
  'guided-learning-ai',
  'routine-guide',
  'blooms-ai',
  'my-groups',
  'flashcard-smart-paste',
];

/** Plan D7: admins pass a default-off flag (preview, or admin-default like `guided-learning-ai`) that has no saved doc yet. */
export const adminPassesMissingDoc = (featureId: string): boolean =>
  ADMIN_PREVIEW_FEATURES.includes(featureId);
