// AUTO-GENERATED by scripts/lti-keygen.mjs — PUBLIC key material only (safe to commit).
// The matching private key lives in Secret Manager secret LTI_TOOL_PRIVATE_KEY.
// Served at https://spartboard.web.app/.well-known/jwks.json by the ltiJwks function.
//
// Rotation: re-run `node scripts/lti-keygen.mjs <new-kid>`, add a new secret version,
// and APPEND the new key to the `keys` array (keep old keys until in-flight JWTs expire).

export interface ToolPublicJwk {
  kty: string;
  n: string;
  e: string;
  use: 'sig';
  alg: 'RS256';
  kid: string;
}

/** kid the signing functions stamp into the JWT header (current/active key). */
export const TOOL_SIGNING_KID = 'spartboard-lti-2026-06';

/** Public JWK Set published at /.well-known/jwks.json for Schoology to verify our JWTs. */
export const TOOL_PUBLIC_JWKS: { keys: ToolPublicJwk[] } = {
  keys: [
    {
      kty: 'RSA',
      n: 'r4CvZL32obw0mfE5NRssi9aIFuoInD4Bv9TQkk0kESaQPqDpEuRJTJhVRej2HVSaPpRaxsuVb6hPDDCXZJqpi5ubkld0gNyBNZSPY_NF_fns1578Oo5qHQlk0m3-n2P5P0wa9mjhrxzJIBMQKkLgauExy07SOQW9mqF8BiVELeZBIRXJ56Z2tD5lqx5LTJPWQbjK8fOI76f2NfZPZ43qxQ-NvrhHaUTrNDA48sIVOqThyXhpumHfks7HW09J4o06DV0o1X6FY6qX-ero_NegsoyHSLXszKCcRjdR7Oe7Tv28E0v2mqVkCWEX_G_Omcgz2D3guZPC1AW1o4C8-5oBhw',
      e: 'AQAB',
      use: 'sig',
      alg: 'RS256',
      kid: 'spartboard-lti-2026-06',
    },
  ],
};
