import type { RandomGroup, SharedGroup } from '@/types';

/** UUID v4 pattern — used to detect synthetic group IDs generated by crypto.randomUUID(). */
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/** A Randomizer group's display name: `sharedGroups` by UUID, else "Group N". */
export const resolveRandomGroupName = (
  group: RandomGroup,
  index: number,
  sharedGroups?: SharedGroup[]
): string => {
  const fallback = `Group ${index + 1}`;
  const rawId = group.id;
  if (!rawId) return fallback;
  if (UUID_RE.test(rawId)) {
    const resolved = (sharedGroups ?? []).find((sg) => sg.id === rawId)?.name;
    return resolved && resolved.trim().length > 0 ? resolved.trim() : fallback;
  }
  // Legacy path: id is already a human-readable string (e.g. "Reading Corner").
  const trimmed = rawId.trim();
  return trimmed.length > 0 ? trimmed : fallback;
};
