import type { BloomsContent } from '@/types';

export const DEFAULT_BLOOMS_CONTENT: BloomsContent = {
  remember: {
    questionStems: [
      'What is the definition of…?',
      'Can you list the steps in…?',
      'Who was involved in…?',
      'When did ___ happen?',
      'Where does ___ take place?',
      'How would you describe…?',
      'Can you recall…?',
      'What do you already know about…?',
    ],
    actionVerbs: [
      'List',
      'Define',
      'Recall',
      'Name',
      'Identify',
      'Describe',
      'Label',
      'Match',
    ],
    activityTypes: [
      'Flashcard review',
      'Matching activity',
      'Fill-in-the-blank worksheet',
      'Vocabulary quiz',
      'Timeline sequencing',
      'Labeling a diagram',
    ],
    assessmentIdeas: [
      'Multiple-choice quiz',
      'True/false questions',
      'Matching definitions to terms',
      'Fill-in-the-blank test',
      'Oral recall quiz',
      'Labeling assessment',
    ],
    iCanStatements: [
      'I can define key vocabulary words.',
      'I can list the main facts about a topic.',
      'I can recall important details from the lesson.',
      'I can identify the parts of a diagram.',
      'I can name the steps in a process.',
      'I can describe what happened in a story.',
    ],
    dokAlignment: [
      'DOK Level 1 — Recall and Reproduction',
      'Requires recalling facts, terms, or simple procedures.',
      'Students retrieve information directly from memory or text.',
      'No transformation of knowledge is needed.',
      'Example: "List the planets in order from the sun."',
      'Example: "Define the term photosynthesis."',
    ],
  },
  understand: {
    questionStems: [
      'How would you summarize…?',
      'Can you explain why…?',
      'What is the main idea of…?',
      'How would you paraphrase…?',
      'What examples can you give of…?',
      'How are ___ and ___ alike?',
      'What does ___ mean in your own words?',
      'Can you explain what is happening in…?',
    ],
    actionVerbs: [
      'Explain',
      'Summarize',
      'Paraphrase',
      'Classify',
      'Interpret',
      'Compare',
      'Infer',
      'Illustrate',
    ],
    activityTypes: [
      'Think-pair-share discussion',
      'Summarizing a passage in own words',
      'Concept mapping',
      'Explaining to a partner',
      'Drawing a picture of a concept',
      'Creating an analogy',
    ],
    assessmentIdeas: [
      'Written summary',
      'Explain-it-to-me exit ticket',
      'Concept map creation',
      'Analogy writing',
      'Short answer explaining "why"',
      'Retelling in own words',
    ],
    iCanStatements: [
      'I can explain a concept in my own words.',
      'I can summarize the main idea of a text.',
      'I can give examples that show my understanding.',
      'I can compare two related ideas.',
      'I can interpret the meaning of a passage.',
      'I can classify items into categories.',
    ],
    dokAlignment: [
      'DOK Level 2 — Skill/Concept',
      'Requires mental processing beyond recall.',
      'Students explain, interpret, or organize information.',
      'Involves making observations and describing patterns.',
      'Example: "Explain why plants need sunlight."',
      'Example: "Summarize the main events of the story."',
    ],
  },
  apply: {
    questionStems: [
      'How would you use ___ in a new situation?',
      'Can you demonstrate how…?',
      'What would happen if…?',
      'How would you solve ___ using what you learned?',
      'Can you show how ___ works?',
      'What approach would you use to…?',
      'How would you apply this rule to…?',
      'Can you give an example from your own life?',
    ],
    actionVerbs: [
      'Apply',
      'Demonstrate',
      'Solve',
      'Use',
      'Implement',
      'Execute',
      'Construct',
      'Model',
    ],
    activityTypes: [
      'Role play or simulation',
      'Hands-on demonstration',
      'Model building',
      'Problem-solving activity',
      'Science experiment',
      'Real-world application project',
    ],
    assessmentIdeas: [
      'Performance task',
      'Lab report',
      'Problem set with real-world scenarios',
      'Demonstration to class',
      'Applied project',
      'Simulation exercise',
    ],
    iCanStatements: [
      'I can use what I learned to solve a new problem.',
      'I can demonstrate a concept with an example.',
      'I can apply a strategy to a real-world situation.',
      'I can build a model that shows how something works.',
      'I can follow a procedure to complete a task.',
      'I can use a formula or rule correctly.',
    ],
    dokAlignment: [
      'DOK Level 2 — Skill/Concept',
      'Requires applying learned procedures to new situations.',
      'Students use knowledge in familiar or slightly new contexts.',
      'May involve following multi-step processes.',
      'Example: "Use the area formula to find the area of this shape."',
      'Example: "Apply the scientific method to test your hypothesis."',
    ],
  },
  analyze: {
    questionStems: [
      'Compare and contrast ___ and ___.',
      'What evidence supports…?',
      'How is ___ related to…?',
      'What are the causes and effects of…?',
      'What patterns do you notice in…?',
      'How would you categorize…?',
      "What is the author's purpose in…?",
      'What conclusions can you draw from…?',
    ],
    actionVerbs: [
      'Analyze',
      'Compare',
      'Contrast',
      'Examine',
      'Differentiate',
      'Categorize',
      'Investigate',
      'Deconstruct',
    ],
    activityTypes: [
      'Venn diagram comparison',
      'Data analysis with charts',
      'Case study investigation',
      'Cause-and-effect mapping',
      'Text structure analysis',
      'Debate preparation with evidence',
    ],
    assessmentIdeas: [
      'Compare/contrast essay',
      'Data interpretation task',
      'Evidence-based argument',
      'Case study analysis',
      'Graphic organizer with reasoning',
      'Source analysis worksheet',
    ],
    iCanStatements: [
      'I can compare and contrast two ideas or texts.',
      'I can identify patterns and relationships in data.',
      'I can find evidence to support a claim.',
      'I can break a complex topic into smaller parts.',
      'I can explain causes and effects.',
      'I can distinguish between fact and opinion.',
    ],
    dokAlignment: [
      'DOK Level 3 — Strategic Thinking',
      'Requires reasoning, planning, and using evidence.',
      'Students examine relationships, patterns, and structures.',
      'Involves higher-order thinking beyond simple application.',
      'Example: "Analyze the data to determine which variable had the greatest effect."',
      'Example: "Compare the themes of two stories and explain how they differ."',
    ],
  },
  evaluate: {
    questionStems: [
      'Do you agree or disagree with…? Why?',
      'What criteria would you use to judge…?',
      'How would you prioritize…?',
      'What is your opinion of…? Defend it.',
      'Which solution is most effective? Why?',
      'How would you rate…?',
      'What are the strengths and weaknesses of…?',
      'Is this source reliable? How do you know?',
    ],
    actionVerbs: [
      'Evaluate',
      'Judge',
      'Justify',
      'Critique',
      'Defend',
      'Prioritize',
      'Assess',
      'Recommend',
    ],
    activityTypes: [
      'Debate',
      'Peer review and feedback',
      'Persuasive writing',
      'Rubric-based self-assessment',
      'Pros and cons analysis',
      'Editorial writing',
    ],
    assessmentIdeas: [
      'Debate performance',
      'Persuasive essay',
      "Critique of a peer's work",
      'Editorial or opinion piece',
      'Self-reflection with rubric',
      'Peer review evaluation',
    ],
    iCanStatements: [
      'I can justify my opinion with evidence.',
      'I can judge the quality of a solution.',
      'I can critique a source for reliability.',
      'I can defend a position in a debate.',
      'I can assess the strengths and weaknesses of an argument.',
      'I can recommend improvements based on criteria.',
    ],
    dokAlignment: [
      'DOK Level 3 — Strategic Thinking',
      'Requires making judgments based on criteria.',
      'Students defend or justify positions with reasoning.',
      'Involves weighing multiple perspectives or solutions.',
      'Example: "Evaluate which renewable energy source is most practical for your community."',
      'Example: "Judge whether the author\'s argument is well-supported."',
    ],
  },
  create: {
    questionStems: [
      'How would you design a new…?',
      'What would you invent to solve…?',
      'Can you compose an original…?',
      'How would you improve…?',
      'What alternative can you propose for…?',
      'Can you develop a plan to…?',
      'How would you combine ___ and ___ to make something new?',
      'What would your own version of ___ look like?',
    ],
    actionVerbs: [
      'Create',
      'Design',
      'Invent',
      'Compose',
      'Develop',
      'Construct',
      'Propose',
      'Formulate',
    ],
    activityTypes: [
      'Design challenge or maker project',
      'Creative writing',
      'Original research project',
      'Invention or prototype building',
      'Film or multimedia production',
      'Composing original music or art',
    ],
    assessmentIdeas: [
      'Original research presentation',
      'Invention or prototype showcase',
      'Portfolio of creative work',
      'Business plan or proposal',
      'Multimedia project',
      'Student-designed assessment',
    ],
    iCanStatements: [
      'I can design a new solution to a problem.',
      'I can compose an original piece of writing.',
      'I can invent something that meets a specific need.',
      'I can develop a plan for a project.',
      'I can create a multimedia presentation.',
      'I can propose an alternative approach.',
    ],
    dokAlignment: [
      'DOK Level 4 — Extended Thinking',
      'Requires synthesizing ideas to produce something original.',
      'Students combine knowledge from multiple sources or disciplines.',
      'Involves planning, investigating, and creating over extended time.',
      'Example: "Design and conduct an experiment to test your own hypothesis."',
      'Example: "Create a public service campaign addressing a community issue."',
    ],
  },
};
