import {
  Volume2,
  Clock,
  Timer,
  PlayCircle,
  TrafficCone,
  Type,
  CheckSquare,
  Users,
  Dices,
  Mic,
  Pencil,
  QrCode,
  Globe,
  BarChart2,
  Video,
  Trophy,
  CloudSun,
  Calendar,
  CalendarDays,
  Utensils,
  BookOpen,
  AppWindow,
  Backpack,
  Sticker,
  Armchair,
  LayoutGrid,
  Shirt,
  Zap,
  FileText,
  ClipboardList,
  Wand2,
  Quote,
  Wind,
  Ruler,
  ListOrdered,
  Music,
  CarFront,
  Speech,
  Smartphone,
  Layers,
  MapPin,
  Share2,
  GraduationCap,
  MessagesSquare,
  Image as ImageIcon,
  Triangle,
  Workflow,
} from 'lucide-react';
import { ToolMetadata, WidgetCategory } from '@/types';

import { RecordIcon } from '@/components/layout/dock/RecordIcon';
import { First5Icon } from '@/components/widgets/First5/First5Icon';

/** Display metadata for the Widget Library's category filter. */
export const WIDGET_CATEGORIES: { value: WidgetCategory; label: string }[] = [
  { value: 'time', label: 'Time & Planning' },
  { value: 'management', label: 'Management' },
  { value: 'instruction', label: 'Instruction' },
  { value: 'interaction', label: 'Interaction' },
  { value: 'media', label: 'Media & Tools' },
  { value: 'fun', label: 'Fun & Rewards' },
];

/**
 * TOOLS is the Dock-facing catalog of user-selectable widgets. It is
 * intentionally NOT exhaustive over the `WidgetType` union — several
 * `WidgetType`s are registered in `WIDGET_COMPONENTS`, `widgetDefaults.ts`,
 * etc., but are deliberately excluded here because they cannot be added
 * directly from the Dock:
 *
 *   - `catalyst-instruction`, `catalyst-visual` — companion sub-widgets
 *     spawned programmatically by the `catalyst` widget.
 *   - `blooms-detail` — read-only companion widget spawned by the
 *     `blooms-taxonomy` widget.
 *   - `mathTool` — individual math-tool instance spawned by the
 *     `mathTools` palette (the palette itself IS in the Dock).
 *   - `custom-widget` — created via the Custom Widget system, surfaced in
 *     the Dock through `CustomWidgetsContext`, not through this catalog.
 *   - `onboarding` — one-time system widget that is added automatically
 *     for new users; never user-selectable.
 *   - `sticker` — handled via a hard-coded branch in
 *     `WidgetRenderer.tsx`; spawned by the `stickers` (StickerBook) widget.
 *
 * If you add a new `WidgetType` that is meant to be user-selectable, add an
 * entry below. If it is programmatically spawned, add it to the list above
 * instead of this array so future maintainers know it was an intentional
 * omission.
 */
export const TOOLS: ToolMetadata[] = [
  {
    type: 'url',
    icon: Globe,
    label: 'Links',
    color: 'bg-emerald-500',
    category: 'media',
    keywords: ['website', 'url', 'bookmark', 'shortcut', 'hyperlink'],
  },
  {
    type: 'soundboard',
    icon: Volume2,
    label: 'Soundboard',
    color: 'bg-indigo-500',
    category: 'fun',
    keywords: ['sound effects', 'audio', 'buttons', 'chime', 'applause'],
  },
  {
    type: 'clock',
    icon: Clock,
    label: 'Clock',
    color: 'bg-blue-500',
    category: 'time',
    keywords: ['time', 'analog', 'digital', 'watch'],
  },
  {
    type: 'time-tool',
    icon: Timer,
    label: 'Timer',
    color: 'bg-red-500',
    category: 'time',
    keywords: ['countdown', 'stopwatch', 'alarm', 'minutes', 'time'],
  },
  {
    type: 'traffic',
    icon: TrafficCone,
    label: 'Traffic',
    color: 'bg-amber-500',
    category: 'management',
    keywords: ['stoplight', 'traffic light', 'noise level', 'red yellow green'],
  },
  {
    type: 'text',
    icon: Type,
    label: 'Note',
    color: 'bg-yellow-400',
    category: 'instruction',
    keywords: ['text', 'sticky note', 'message', 'announcement', 'writing'],
  },
  {
    type: 'checklist',
    icon: CheckSquare,
    label: 'Tasks',
    color: 'bg-green-500',
    category: 'management',
    keywords: ['checklist', 'to-do', 'todo', 'agenda', 'steps'],
  },
  {
    type: 'random',
    icon: Users,
    label: 'Random',
    color: 'bg-indigo-500',
    category: 'interaction',
    keywords: ['picker', 'name picker', 'wheel', 'chooser', 'student selector'],
  },
  {
    type: 'dice',
    icon: Dices,
    label: 'Dice',
    color: 'bg-purple-500',
    category: 'fun',
    keywords: ['roll', 'random number', 'game', 'probability'],
  },
  {
    type: 'sound',
    icon: Mic,
    label: 'Noise',
    color: 'bg-pink-500',
    category: 'management',
    keywords: ['noise meter', 'volume', 'decibel', 'loudness', 'microphone'],
  },
  {
    type: 'drawing',
    icon: Pencil,
    label: 'Draw',
    color: 'bg-cyan-500',
    category: 'media',
    keywords: ['whiteboard', 'sketch', 'paint', 'annotate', 'canvas'],
  },
  {
    type: 'qr',
    icon: QrCode,
    label: 'QR',
    color: 'bg-slate-700',
    category: 'media',
    keywords: ['qr code', 'scan', 'link', 'barcode'],
  },
  {
    type: 'embed',
    icon: Globe,
    label: 'Embed',
    color: 'bg-sky-600',
    category: 'media',
    keywords: ['iframe', 'website', 'youtube', 'video', 'web page'],
  },
  {
    type: 'poll',
    icon: BarChart2,
    label: 'Poll',
    color: 'bg-orange-500',
    category: 'interaction',
    keywords: ['vote', 'survey', 'question', 'opinion', 'results'],
  },
  {
    type: 'activity-wall',
    icon: MessagesSquare,
    label: 'Activity Wall',
    color: 'bg-fuchsia-600',
    category: 'interaction',
    keywords: ['padlet', 'posts', 'sharing', 'discussion', 'board'],
  },
  {
    type: 'webcam',
    icon: Video,
    label: 'Camera',
    color: 'bg-gray-800',
    category: 'media',
    keywords: ['webcam', 'document camera', 'video', 'mirror'],
  },
  {
    type: 'scoreboard',
    icon: Trophy,
    label: 'Scores',
    color: 'bg-yellow-600',
    category: 'fun',
    keywords: ['points', 'teams', 'game', 'competition', 'tally'],
  },
  {
    type: 'expectations',
    icon: LayoutGrid,
    label: 'Expectations',
    color: 'bg-emerald-600',
    category: 'management',
    keywords: ['rules', 'behavior', 'norms', 'voice level', 'champs'],
  },
  {
    type: 'weather',
    icon: CloudSun,
    label: 'Weather',
    color: 'bg-sky-400',
    category: 'time',
    keywords: ['forecast', 'temperature', 'rain', 'snow', 'outside'],
  },
  {
    type: 'schedule',
    icon: Calendar,
    label: 'Schedule',
    color: 'bg-teal-600',
    category: 'time',
    keywords: ['daily schedule', 'agenda', 'periods', 'routine', 'plan'],
  },
  {
    type: 'specialist-schedule',
    icon: CalendarDays,
    label: 'Specialist',
    color: 'bg-teal-700',
    category: 'time',
    keywords: ['specials', 'rotation', 'gym', 'art', 'music schedule'],
  },
  {
    type: 'graphic-organizer',
    icon: LayoutGrid,
    label: 'Organizer',
    color: 'bg-indigo-500',
    category: 'instruction',
    keywords: ['venn diagram', 'kwl', 'chart', 'brainstorm', 'thinking map'],
  },
  {
    type: 'calendar',
    icon: Calendar,
    label: 'Events',
    color: 'bg-rose-500',
    category: 'time',
    keywords: ['calendar', 'google calendar', 'upcoming', 'dates'],
  },
  {
    type: 'lunchCount',
    icon: Utensils,
    label: 'Lunch',
    color: 'bg-orange-600',
    category: 'management',
    keywords: ['lunch count', 'meal', 'attendance', 'cafeteria', 'food'],
  },
  {
    type: 'classes',
    icon: Users,
    label: 'Class',
    color: 'bg-indigo-600',
    category: 'management',
    keywords: ['roster', 'students', 'attendance', 'groups'],
  },
  {
    type: 'car-rider-pro',
    icon: CarFront,
    label: 'Car Rider',
    color: 'bg-blue-500',
    category: 'management',
    keywords: ['pickup', 'dismissal', 'carpool', 'parent pickup'],
  },
  {
    type: 'blending-board',
    icon: Speech,
    label: 'Blending Board',
    color: 'bg-violet-500',
    category: 'instruction',
    keywords: ['phonics', 'sounds', 'reading', 'letters', 'decoding'],
  },
  {
    type: 'first-5',
    icon: First5Icon,
    label: 'First 5',
    color: 'bg-amber-500',
    category: 'instruction',
    keywords: ['bell ringer', 'warm up', 'do now', 'starter', 'entry task'],
  },
  {
    type: 'instructionalRoutines',
    icon: BookOpen,
    label: 'Routines',
    color: 'bg-brand-blue-primary',
    category: 'instruction',
    keywords: ['instructional routines', 'protocols', 'strategies', 'lesson'],
  },
  {
    type: 'miniApp',
    icon: AppWindow,
    label: 'Mini Apps',
    color: 'bg-violet-600',
    category: 'media',
    keywords: ['apps', 'ai', 'generator', 'games', 'interactive'],
  },
  {
    type: 'materials',
    icon: Backpack,
    label: 'Materials',
    color: 'bg-rose-600',
    category: 'management',
    keywords: ['supplies', 'what to bring', 'pencil', 'notebook', 'backpack'],
  },
  {
    type: 'stickers',
    icon: Sticker,
    label: 'Stickers',
    color: 'bg-pink-500',
    category: 'fun',
    keywords: ['decorations', 'emoji', 'images', 'rewards', 'clip art'],
  },
  {
    type: 'seating-chart',
    icon: Armchair,
    label: 'Seating',
    color: 'bg-teal-500',
    category: 'management',
    keywords: ['seating chart', 'desks', 'assigned seats', 'classroom layout'],
  },
  {
    type: 'catalyst',
    icon: Zap,
    label: 'Catalyst',
    color: 'bg-indigo-600',
    category: 'instruction',
    keywords: ['lesson launcher', 'directions', 'instructions', 'activity'],
  },
  {
    type: 'smartNotebook',
    icon: BookOpen,
    label: 'Notebook',
    color: 'bg-green-600',
    category: 'instruction',
    keywords: ['smart notebook', 'slides', 'lessons', 'pages', 'spartnb'],
  },
  {
    type: 'recessGear',
    icon: Shirt,
    label: 'Recess Gear',
    color: 'bg-emerald-500',
    category: 'management',
    keywords: ['coats', 'boots', 'outside', 'clothing', 'winter gear'],
  },
  {
    type: 'pdf',
    icon: FileText,
    label: 'PDF Viewer',
    color: 'bg-red-700',
    category: 'media',
    keywords: ['pdf', 'document', 'worksheet', 'file', 'reader'],
  },
  {
    type: 'quiz',
    icon: ClipboardList,
    label: 'Quiz',
    color: 'bg-violet-600',
    category: 'interaction',
    keywords: ['test', 'assessment', 'kahoot', 'questions', 'live quiz'],
  },
  {
    type: 'talking-tool',
    icon: Quote,
    label: 'Talking Tool',
    color: 'bg-sky-500',
    category: 'interaction',
    keywords: ['sentence stems', 'discussion', 'accountable talk', 'speaking'],
    defaultWidth: 500,
    defaultHeight: 450,
    minWidth: 400,
    minHeight: 350,
  },
  {
    type: 'breathing',
    icon: Wind,
    label: 'Breathing',
    color: 'bg-sky-400',
    category: 'management',
    keywords: ['calm', 'mindfulness', 'relax', 'sel', 'brain break'],
  },
  {
    type: 'mathTools',
    icon: Ruler,
    label: 'Math',
    color: 'bg-teal-500',
    category: 'instruction',
    keywords: [
      'ruler',
      'protractor',
      'calculator',
      'manipulatives',
      'geometry',
    ],
  },
  {
    type: 'nextUp',
    icon: ListOrdered,
    label: 'Next Up',
    color: 'bg-brand-blue-primary',
    category: 'management',
    keywords: ['queue', 'turn', 'line', 'waiting list', 'who is next'],
  },
  {
    type: 'numberLine',
    icon: ListOrdered,
    label: 'Number Line',
    color: 'bg-blue-600',
    category: 'instruction',
    keywords: ['math', 'counting', 'integers', 'numbers'],
  },
  {
    type: 'music',
    icon: Music,
    label: 'Music',
    color: 'bg-emerald-500',
    category: 'media',
    keywords: ['spotify', 'songs', 'playlist', 'background music', 'stations'],
  },
  {
    type: 'record',
    icon: RecordIcon,
    label: 'Record',
    color: 'bg-red-500',
    category: 'media',
    keywords: ['screen recording', 'capture', 'video', 'screencast'],
  },

  {
    type: 'magic',
    icon: Wand2,
    label: 'Magic',
    color: 'bg-gradient-to-br from-indigo-500 to-purple-600',
    category: 'media',
    keywords: ['magic layout', 'arrange', 'auto layout', 'organize board'],
  },
  {
    type: 'remote',
    icon: Smartphone,
    label: 'Remote',
    color: 'bg-slate-800',
    category: 'media',
    keywords: ['remote control', 'phone', 'mobile', 'control board'],
  },
  {
    type: 'reveal-grid',
    icon: Layers,
    label: 'Reveal',
    color: 'bg-blue-500',
    category: 'instruction',
    keywords: ['hidden picture', 'mystery image', 'guessing game', 'uncover'],
  },
  {
    type: 'syntax-framer',
    icon: Type,
    label: 'Syntax Framer',
    color: 'bg-indigo-500',
    category: 'instruction',
    keywords: ['sentence frames', 'grammar', 'writing', 'language'],
  },
  {
    type: 'hotspot-image',
    icon: MapPin,
    label: 'Hotspot Image',
    color: 'bg-emerald-500',
    category: 'instruction',
    keywords: ['interactive image', 'labels', 'diagram', 'clickable'],
  },
  {
    type: 'concept-web',
    icon: Share2,
    label: 'Concept Web',
    color: 'bg-violet-500',
    category: 'instruction',
    keywords: ['mind map', 'brainstorm', 'web', 'connections', 'ideas'],
  },
  {
    type: 'starter-pack',
    icon: Wand2,
    label: 'Starter Packs',
    color: 'bg-indigo-600',
    category: 'media',
    keywords: ['templates', 'presets', 'board setup', 'bundles'],
  },
  {
    type: 'video-activity',
    icon: PlayCircle,
    label: 'Video Activity',
    color: 'bg-red-500',
    category: 'interaction',
    keywords: ['edpuzzle', 'video questions', 'youtube', 'watch and answer'],
    defaultWidth: 640,
    defaultHeight: 560,
    minWidth: 480,
    minHeight: 400,
  },
  {
    type: 'guided-learning',
    icon: GraduationCap,
    label: 'Guided Learning',
    color: 'bg-indigo-600',
    category: 'interaction',
    keywords: ['self paced', 'lessons', 'steps', 'tutorial', 'practice'],
    defaultWidth: 720,
    defaultHeight: 520,
    minWidth: 480,
    minHeight: 380,
  },
  {
    type: 'countdown',
    icon: CalendarDays,
    label: 'Countdown',
    color: 'bg-orange-500',
    category: 'time',
    keywords: ['days until', 'event countdown', 'field trip', 'last day'],
  },
  {
    type: 'work-symbols',
    icon: ImageIcon,
    label: 'Work Symbols',
    color: 'bg-violet-500',
    category: 'management',
    keywords: ['work mode', 'voice level', 'independent', 'partner', 'group'],
  },
  {
    type: 'blooms-taxonomy',
    icon: Triangle,
    label: "Bloom's Taxonomy",
    color: 'bg-indigo-600',
    category: 'instruction',
    keywords: ['blooms', 'thinking levels', 'questioning', 'rigor', 'depth'],
  },
  {
    type: 'need-do-put-then',
    icon: Workflow,
    label: 'Need / Do / Put / Then',
    color: 'bg-cyan-600',
    category: 'management',
    keywords: ['directions', 'task board', 'steps', 'what to do'],
  },
  {
    type: 'stations',
    icon: LayoutGrid,
    label: 'Stations',
    color: 'bg-emerald-500',
    category: 'management',
    keywords: ['centers', 'rotations', 'groups', 'small group'],
  },
];
