import {
  Clock,
  Timer,
  TrafficCone,
  Type,
  CheckSquare,
  Users,
  Dices,
  Mic,
  Pencil,
  QrCode,
  Globe,
  BarChart2,
  Video,
  Trophy,
  CloudSun,
  Calendar,
  Utensils,
  BookOpen,
  AppWindow,
  Backpack,
  Sticker,
  Armchair,
  LayoutGrid,
  Shirt,
  Zap,
  FileText,
  ClipboardList,
  Wand2,
  Wind,
  Ruler,
} from 'lucide-react';
import { ToolMetadata } from '../types';

import { RecordIcon } from '../components/layout/dock/RecordIcon';

export const TOOLS: ToolMetadata[] = [
  { type: 'clock', icon: Clock, label: 'Clock', color: 'bg-blue-500' },
  { type: 'time-tool', icon: Timer, label: 'Timer', color: 'bg-red-500' },
  {
    type: 'traffic',
    icon: TrafficCone,
    label: 'Traffic',
    color: 'bg-amber-500',
  },
  { type: 'text', icon: Type, label: 'Note', color: 'bg-yellow-400' },
  {
    type: 'checklist',
    icon: CheckSquare,
    label: 'Tasks',
    color: 'bg-green-500',
  },
  { type: 'random', icon: Users, label: 'Random', color: 'bg-indigo-500' },
  { type: 'dice', icon: Dices, label: 'Dice', color: 'bg-purple-500' },
  { type: 'sound', icon: Mic, label: 'Noise', color: 'bg-pink-500' },
  { type: 'drawing', icon: Pencil, label: 'Draw', color: 'bg-cyan-500' },
  { type: 'qr', icon: QrCode, label: 'QR', color: 'bg-slate-700' },
  { type: 'embed', icon: Globe, label: 'Embed', color: 'bg-sky-600' },
  { type: 'poll', icon: BarChart2, label: 'Poll', color: 'bg-orange-500' },
  { type: 'webcam', icon: Video, label: 'Camera', color: 'bg-gray-800' },
  { type: 'scoreboard', icon: Trophy, label: 'Scores', color: 'bg-yellow-600' },
  {
    type: 'expectations',
    icon: LayoutGrid,
    label: 'Expectations',
    color: 'bg-emerald-600',
  },
  { type: 'weather', icon: CloudSun, label: 'Weather', color: 'bg-sky-400' },
  { type: 'schedule', icon: Calendar, label: 'Schedule', color: 'bg-teal-600' },
  { type: 'calendar', icon: Calendar, label: 'Events', color: 'bg-rose-500' },
  {
    type: 'lunchCount',
    icon: Utensils,
    label: 'Lunch',
    color: 'bg-orange-600',
  },
  { type: 'classes', icon: Users, label: 'Class', color: 'bg-indigo-600' },
  {
    type: 'instructionalRoutines',
    icon: BookOpen,
    label: 'Routines',
    color: 'bg-brand-blue-primary',
  },
  {
    type: 'miniApp',
    icon: AppWindow,
    label: 'Mini Apps',
    color: 'bg-violet-600',
  },
  {
    type: 'materials',
    icon: Backpack,
    label: 'Materials',
    color: 'bg-rose-600',
  },
  { type: 'stickers', icon: Sticker, label: 'Stickers', color: 'bg-pink-500' },
  {
    type: 'seating-chart',
    icon: Armchair,
    label: 'Seating',
    color: 'bg-teal-500',
  },
  { type: 'catalyst', icon: Zap, label: 'Catalyst', color: 'bg-indigo-600' },
  {
    type: 'smartNotebook',
    icon: BookOpen,
    label: 'Notebook',
    color: 'bg-green-600',
  },
  {
    type: 'recessGear',
    icon: Shirt,
    label: 'Recess Gear',
    color: 'bg-emerald-500',
  },
  { type: 'pdf', icon: FileText, label: 'PDF Viewer', color: 'bg-red-700' },
  { type: 'quiz', icon: ClipboardList, label: 'Quiz', color: 'bg-violet-600' },
  { type: 'breathing', icon: Wind, label: 'Breathing', color: 'bg-sky-400' },
  {
    type: 'mathTools',
    icon: Ruler,
    label: 'Math Tools',
    color: 'bg-purple-600',
  },
  { type: 'record', icon: RecordIcon, label: 'Record', color: 'bg-red-500' },
  {
    type: 'magic',
    icon: Wand2,
    label: 'Magic',
    color: 'bg-gradient-to-br from-indigo-500 to-purple-600',
  },
];
