/**
 * Shared builder for the `PlcLinkage` sub-object attached to a quiz
 * assignment when the teacher opts into "Share results with <PLC>".
 *
 * Used by the QuizWidget assign flow, the Classroom add-on, the LTI picker
 * and the PLC library pickup so every call site builds the same shape. The
 * linkage exists whenever a PLC is chosen; pooled results never depend on a
 * sheet (D2). Callers that still want a per-assignment Google Sheet pass a
 * token; the widget no longer does, so `googleAccessToken` is optional.
 */

import type { Plc, PlcLinkage } from '@/types';
import { QuizDriveService } from '@/utils/quizDriveService';
import { getPlcMemberEmails, getPlcTeammateEmails } from '@/utils/plc';

export interface BuildPlcLinkageArgs {
  /**
   * The PLC the teacher chose to share with. `undefined` (e.g. PLC mode off
   * or the PLC snapshot hasn't hydrated) yields no linkage.
   */
  plc: Plc | undefined;
  /** Title of the quiz being assigned — names the auto-created sheet. */
  quizTitle: string;
  /** Owning teacher's Firebase uid — used to skip self when granting access. */
  selfUid: string;
  /**
   * Drive/Sheets access token. Only needed to auto-create a shared sheet;
   * when absent (and no manual URL is supplied) the linkage has no sheet.
   */
  googleAccessToken?: string | null;
  /**
   * Teacher-pasted sheet URL, if any. When present we skip auto-create and
   * use it verbatim (the legacy manual-paste flow).
   */
  manualSheetUrl?: string;
}

export interface BuildPlcLinkageResult {
  /** The assembled linkage, or `undefined` when no PLC was supplied. */
  linkage: PlcLinkage | undefined;
  /**
   * Non-null when sheet auto-create failed. The linkage is still returned
   * (without `sheetUrl`); the caller surfaces this so the teacher can add a
   * sheet later.
   */
  error: Error | null;
}

/**
 * Assemble the `PlcLinkage`, resolving the optional shared sheet first.
 * Never throws — sheet auto-create failures are caught and returned on
 * `error`.
 */
export async function buildPlcLinkage(
  args: BuildPlcLinkageArgs
): Promise<BuildPlcLinkageResult> {
  const { plc, quizTitle, selfUid, googleAccessToken, manualSheetUrl } = args;

  if (!plc) {
    return { linkage: undefined, error: null };
  }

  // Auto-create a per-assignment sheet when no manual URL was pasted and a
  // Sheets token is available. Failure only costs the sheet, not the link.
  let resolvedSheetUrl = manualSheetUrl;
  let autoGenerated = false;
  let error: Error | null = null;
  if (!resolvedSheetUrl && googleAccessToken) {
    try {
      const driveService = new QuizDriveService(googleAccessToken);
      const created = await driveService.createPlcSheetAndShare({
        plcName: plc.name,
        quizTitle,
        memberEmailsToShareWith: getPlcTeammateEmails(plc, selfUid),
      });
      resolvedSheetUrl = created.url;
      autoGenerated = true;
    } catch (err) {
      error = err instanceof Error ? err : new Error(String(err));
    }
  }

  const linkage: PlcLinkage | undefined = plc.name
    ? {
        id: plc.id,
        name: plc.name,
        // Full roster snapshot (including self) for downstream importers.
        memberEmails: getPlcMemberEmails(plc),
        ...(resolvedSheetUrl ? { sheetUrl: resolvedSheetUrl } : {}),
        // Marks system-created sheets so settings keep "Auto-Generated" on.
        ...(autoGenerated ? { autoGenerated: true } : {}),
      }
    : undefined;

  return { linkage, error };
}
