/**
 * Shared builder for the `PlcLinkage` sub-object attached to a quiz
 * assignment when the teacher opts into "Share with PLC".
 *
 * Extracted from `QuizWidget`'s inline assign flow so the Google Classroom
 * add-on attach path (`components/classroomAddon/TeacherDiscoveryRoute.tsx`)
 * can build the EXACT same linkage without forking the logic. Both call
 * sites resolve the shared sheet (auto-create a fresh per-assignment Google
 * Sheet, or pass through a manually-pasted URL), snapshot the PLC name +
 * member emails, and assemble the linkage iff every required field resolves.
 *
 * Each PLC assignment gets its own unique sheet — we do NOT reuse a single
 * cached sheet across the PLC. A failed sheet auto-create falls through to
 * the manual-paste behaviour (empty URL ⇒ no linkage) and is surfaced to
 * the caller via the returned `error` so the teacher can recover.
 */

import type { Plc, PlcLinkage } from '@/types';
import { QuizDriveService } from '@/utils/quizDriveService';
import { getPlcMemberEmails, getPlcTeammateEmails } from '@/utils/plc';

export interface BuildPlcLinkageArgs {
  /**
   * The PLC the teacher chose to share with. `undefined` (e.g. PLC mode off
   * or the PLC snapshot hasn't hydrated) yields no linkage.
   */
  plc: Plc | undefined;
  /** Title of the quiz being assigned — names the auto-created sheet. */
  quizTitle: string;
  /** Owning teacher's Firebase uid — used to skip self when granting access. */
  selfUid: string;
  /**
   * Drive/Sheets access token. Required to auto-create the shared sheet;
   * when absent (and no manual URL is supplied) no linkage is built.
   */
  googleAccessToken: string | null | undefined;
  /**
   * Teacher-pasted sheet URL, if any. When present we skip auto-create and
   * use it verbatim (the legacy manual-paste flow).
   */
  manualSheetUrl?: string;
}

export interface BuildPlcLinkageResult {
  /**
   * The assembled linkage, or `undefined` when PLC mode is off / a required
   * field couldn't be resolved (missing PLC, missing sheet URL, etc.). A
   * partial linkage is intentionally never returned — the read mapper would
   * strip it on next load anyway.
   */
  linkage: PlcLinkage | undefined;
  /**
   * Non-null when sheet auto-create failed. The caller surfaces this (toast /
   * status log) and falls through to the manual-paste behaviour. Distinct
   * from "PLC mode off" — `linkage` is undefined in both cases, but only an
   * auto-create failure sets `error`.
   */
  error: Error | null;
}

/**
 * Resolve the shared sheet + assemble the `PlcLinkage`. Mirrors the inline
 * logic that used to live in `QuizWidget`'s `onAssign`. Never throws — sheet
 * auto-create failures are caught and returned on `error` so the assignment
 * can still be created without PLC linkage.
 */
export async function buildPlcLinkage(
  args: BuildPlcLinkageArgs
): Promise<BuildPlcLinkageResult> {
  const { plc, quizTitle, selfUid, googleAccessToken, manualSheetUrl } = args;

  if (!plc) {
    return { linkage: undefined, error: null };
  }

  // PLC auto-create: when the teacher didn't paste a manual URL, create a
  // fresh Google Sheet under the teacher's Drive for THIS assignment and
  // share it with every teammate. Each PLC assignment gets its own unique
  // sheet. Failures here don't block the assignment — we fall through to the
  // manual-paste behaviour (empty URL ⇒ no linkage) and report `error`.
  let resolvedSheetUrl = manualSheetUrl;
  let autoGenerated = false;
  let error: Error | null = null;
  if (!resolvedSheetUrl && googleAccessToken) {
    try {
      const driveService = new QuizDriveService(googleAccessToken);
      const created = await driveService.createPlcSheetAndShare({
        plcName: plc.name,
        quizTitle,
        memberEmailsToShareWith: getPlcTeammateEmails(plc, selfUid),
      });
      resolvedSheetUrl = created.url;
      autoGenerated = true;
    } catch (err) {
      error = err instanceof Error ? err : new Error(String(err));
    }
  }

  // Build the linkage iff every required field resolved. Partial resolution
  // (e.g. auto-create failed and no manual URL) falls back to non-PLC linkage.
  const linkage: PlcLinkage | undefined =
    plc.name && resolvedSheetUrl
      ? {
          id: plc.id,
          name: plc.name,
          sheetUrl: resolvedSheetUrl,
          // Snapshot the full PLC roster (including self) so the share doc
          // carries enough info for downstream importers to render the
          // membership list without a separate read.
          memberEmails: getPlcMemberEmails(plc),
          // Mark sheets the system created (vs. teacher-pasted) so the
          // settings modal can keep the "Auto-Generated" toggle ON for this
          // assignment and for any PLC peer who imports.
          ...(autoGenerated ? { autoGenerated: true } : {}),
        }
      : undefined;

  return { linkage, error };
}
