/**
 * Shared helpers for the in-tab "+ Assign Quiz" / "+ Assign Video" wizards
 * on the PLC Assignments → Library sub-tab. Both wizards converged on the
 * same formatter + validity check; the originals were inlined verbatim in
 * `PlcNewQuizAssignmentModal.tsx` and `PlcNewVideoActivityAssignmentModal.tsx`
 * — pulled out here so a fix to either stays in one place.
 */

/** Locale-aware short date for the picker `metaLine`. Returns `''` on bad input. */
export function formatShortDate(ms: number): string {
  try {
    return new Date(ms).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  } catch {
    return '';
  }
}

/**
 * Predicate for the in-tab wizard's manual Sheet-URL field. True iff the
 * user has typed something non-empty that doesn't look like a Google
 * Sheets URL. Empty input is treated as "no URL attached" (the
 * Auto-Generated toggle covers the URL-less path).
 */
export function isPlcSheetUrlInvalid(
  rawUrl: string,
  useAutoGenerated: boolean
): boolean {
  if (useAutoGenerated) return false;
  const trimmed = rawUrl.trim();
  if (!trimmed) return false;
  return !trimmed.startsWith('https://docs.google.com/spreadsheets/');
}
