/**
 * PlcNewQuizAssignmentModal — in-tab "+ Assign Quiz" wizard for the PLC
 * dashboard's Assignments → Library sub-tab.
 *
 * Two-step flow:
 *
 *   1. Pick a quiz from the teacher's personal library
 *      (reuses `PlcSharePickerModal`).
 *   2. Slimmed configure step (Task 10): class/period picker + due-date +
 *      read-only behavior summary sourced from `getQuizBehavior(pickedQuiz)`.
 *      Mode picker, toggles, gamification, and attempt-limit controls have
 *      been removed — behavior lives on the quiz and is edited there.
 *      The PLC sharing slot (auto-sheet + teacher name) is retained.
 *
 * On submit, mirrors `QuizWidget.handleAssignConfirm` (the kebab path):
 *
 *   a. Auto-create a PLC sheet if Drive is connected and no manual URL
 *      was provided.
 *   b. Resolve the `PlcLinkage` sub-object (id, name, sheetUrl,
 *      memberEmails, autoGenerated).
 *   c. If the source quiz has no `sync.groupId`, mint one with
 *      `plcId` set (so PLC-aware tooling can find it), attach the sync
 *      linkage to the local quiz, and pass the new id through as
 *      `plcTemplateSyncGroupId`. This is what lets teammates who later
 *      "Add to my board" land on the same canonical content.
 *   d. `createAssignment` with `settings.plc` set and behavior sourced
 *      from `getQuizBehavior(pickedQuiz)` — the hook handles the
 *      `assignment_index` entry (`kind: 'quiz'`) AND the
 *      `assignments` template write, so the In-progress sub-tab picks
 *      up the new row via its live snapshot.
 *
 * Known orphan-group gap: if step (d) fails after step (c) succeeded the
 * personal copy retains a self-only sync linkage and the PLC's
 * `assignment_index` / template stay empty. There's no
 * `detachSyncLinkage` API today, so we log under
 * `newPlcAssignment.orphanedGroup` for observability and surface a toast.
 * Same posture PR #1595 took for the share picker.
 */

import React, { useCallback, useMemo, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Calendar, X } from 'lucide-react';
import type {
  AssignmentMode,
  ClassRoster,
  Plc,
  PlcLinkage,
  QuizMetadata,
  QuizSessionOptions,
} from '@/types';
import { useAuth } from '@/context/useAuth';
import { useDashboard } from '@/context/useDashboard';
import { useQuiz } from '@/hooks/useQuiz';
import { useQuizAssignments } from '@/hooks/useQuizAssignments';
import {
  callLeaveSyncedQuizGroup,
  createSyncedQuizGroup,
} from '@/hooks/useSyncedQuizGroups';
import { getPlcMemberEmails, getPlcTeammateEmails } from '@/utils/plc';
import { QuizDriveService } from '@/utils/quizDriveService';
import { deriveSessionTargetsFromRosters } from '@/utils/resolveAssignmentTargets';
import { logError } from '@/utils/logError';
import { getQuizBehavior, formatBehaviorSummary } from '@/utils/quizBehavior';
import { AssignClassPicker } from '@/components/common/AssignClassPicker';
import {
  makeEmptyPickerValue,
  type AssignClassPickerValue,
} from '@/components/common/AssignClassPicker.helpers';
import {
  PlcSharePickerModal,
  type PlcSharePickerItem,
} from './PlcSharePickerModal';
import { PlcNewAssignmentSharingSlot } from './PlcNewAssignmentSharingSlot';
import { formatShortDate, isPlcSheetUrlInvalid } from './newAssignmentHelpers';

interface PlcNewQuizAssignmentModalProps {
  plc: Plc;
  /**
   * Org-wide assignment mode frozen onto the new assignment + session.
   * Defaults to `'submissions'`. The PLC dashboard reads it from the
   * authenticated teacher's `appSettings` and forwards it here so the
   * new assignment matches every other assignment created in this org.
   */
  assignmentMode?: AssignmentMode;
  onClose: () => void;
  /**
   * Fired after the assignment write + index write commit. The parent
   * uses this to surface a follow-up toast and to optionally chain
   * straight into the post-create "Edit all settings…" hand-off.
   */
  onCreated?: (info: { assignmentId: string; quizTitle: string }) => void;
}

/** Slimmed configure-step options (Task 10). Behavior is on the quiz. */
interface QuizAssignOptions {
  teacherName: string;
  plcSheetUrl: string;
  picker: AssignClassPickerValue;
}

function buildDefaultOptions(defaultTeacherName?: string): QuizAssignOptions {
  return {
    teacherName: defaultTeacherName ?? '',
    plcSheetUrl: '',
    picker: makeEmptyPickerValue(),
  };
}

export const PlcNewQuizAssignmentModal: React.FC<
  PlcNewQuizAssignmentModalProps
> = ({ plc, assignmentMode = 'submissions', onClose, onCreated }) => {
  const { t } = useTranslation();
  const { user, googleAccessToken, ensureGoogleScope } = useAuth();
  const { addToast, rosters } = useDashboard();
  const { quizzes, loadQuizData, attachSyncLinkage, isDriveConnected } =
    useQuiz(user?.uid);
  const { createAssignment } = useQuizAssignments(user?.uid);

  const [step, setStep] = useState<'pick' | 'configure'>('pick');
  const [pickedQuiz, setPickedQuiz] = useState<QuizMetadata | null>(null);
  const [options, setOptions] = useState<QuizAssignOptions>(() =>
    buildDefaultOptions(user?.displayName ?? undefined)
  );
  // Due date state (epoch ms or null)
  const [dueAt, setDueAt] = useState<number | null>(null);
  // Auto-Generated PLC Sheet toggle: ON by default; flipping OFF reveals
  // the manual-URL field. Mirrors the QuizWidget AssignPlcSlot behavior.
  const [useAutoGenerated, setUseAutoGenerated] = useState(true);
  // Synchronous submit guard. State alone isn't enough — a double-click
  // can fire two submit handlers before React commits the first
  // setState. See `PlcSharePickerModal.handlePick` for the same pattern.
  const submittingRef = useRef(false);
  const [submitting, setSubmitting] = useState(false);

  const pickerItems: PlcSharePickerItem[] = useMemo(
    () =>
      quizzes.map((quiz) => ({
        id: quiz.id,
        title: quiz.title,
        metaLine: t('plcDashboard.newAssignment.quiz.metaLine', {
          count: quiz.questionCount ?? 0,
          date: formatShortDate(quiz.updatedAt ?? quiz.createdAt ?? 0),
          defaultValue: '{{count}} questions · {{date}}',
        }),
      })),
    [quizzes, t]
  );

  const plcSheetUrlInvalid = isPlcSheetUrlInvalid(
    options.plcSheetUrl,
    useAutoGenerated
  );

  const handlePick = useCallback(
    (quizId: string): Promise<void> => {
      const meta = quizzes.find((q) => q.id === quizId);
      if (!meta) {
        addToast(
          t('plcDashboard.newAssignment.quiz.missingFromLibrary', {
            defaultValue: 'That quiz is no longer in your library.',
          }),
          'error'
        );
        return Promise.resolve();
      }
      setPickedQuiz(meta);
      setStep('configure');
      return Promise.resolve();
    },
    [addToast, quizzes, t]
  );

  const handleSubmit = useCallback(async () => {
    if (submittingRef.current) return;
    if (!pickedQuiz || !user) return;
    submittingRef.current = true;
    setSubmitting(true);

    let createdSyncGroupId: string | null = null;
    let linkageAttached = false;
    try {
      // Load Drive content up front so a sync-group mint never lands
      // without questions, and so any Drive auth issue surfaces a toast
      // before we touch shared state.
      const data = await loadQuizData(pickedQuiz.driveFileId);

      const visibleRosterIds = new Set(
        rosters.filter((r) => !r.loadError).map((r) => r.id)
      );
      const validRosterIds = options.picker.rosterIds.filter((id) =>
        visibleRosterIds.has(id)
      );
      const selectedRosters: ClassRoster[] = rosters.filter((r) =>
        validRosterIds.includes(r.id)
      );
      const derived = deriveSessionTargetsFromRosters(selectedRosters);

      // PLC sheet resolution: auto-create when the toggle is ON and no
      // manual URL was provided. Mirrors `QuizWidget.handleAssignConfirm`
      // — best-effort, toasts on failure, falls through to "no sheet
      // attached" rather than blocking the assignment.
      const trimmedManualUrl = options.plcSheetUrl.trim();
      let resolvedSheetUrl = useAutoGenerated ? '' : trimmedManualUrl;
      let sheetAutoGenerated = false;
      // Acquire the Sheets scope on demand (Path B) before auto-creating the
      // shared sheet: silent for already-granted users, a one-time consent
      // popup for never-granted (this Save click is a user gesture). A null
      // token (declined / no Google access) skips creation — same best-effort
      // fall-through as before.
      const sheetsToken =
        useAutoGenerated && !resolvedSheetUrl
          ? await ensureGoogleScope('spreadsheets', { interactive: true })
          : null;
      if (useAutoGenerated && !resolvedSheetUrl && sheetsToken) {
        try {
          const driveService = new QuizDriveService(sheetsToken);
          const created = await driveService.createPlcSheetAndShare({
            plcName: plc.name,
            quizTitle: pickedQuiz.title,
            memberEmailsToShareWith: getPlcTeammateEmails(plc, user.uid),
          });
          resolvedSheetUrl = created.url;
          sheetAutoGenerated = true;
        } catch (err) {
          logError('PlcNewQuizAssignmentModal.sheetAutoCreate', err, {
            plcId: plc.id,
            quizId: pickedQuiz.id,
          });
          addToast(
            err instanceof Error && err.message
              ? err.message
              : t('plcDashboard.newAssignment.quiz.sheetAutoCreateFailed', {
                  defaultValue:
                    'Could not create the shared PLC sheet — you can still paste a URL manually, or save without a sheet.',
                }),
            'error'
          );
        }
      }

      const plcLinkage: PlcLinkage = {
        id: plc.id,
        name: plc.name,
        sheetUrl: resolvedSheetUrl,
        memberEmails: getPlcMemberEmails(plc),
        ...(sheetAutoGenerated ? { autoGenerated: true } : {}),
      };

      // Promote-to-synced: if the source quiz has no `sync.groupId`,
      // mint one with `plcId` set so peer importers landing on the PLC
      // template can read the canonical group. Mirrors the QuizWidget
      // `plcLinkage && !plcTemplateSyncGroupId` branch.
      let plcTemplateSyncGroupId: string | undefined = pickedQuiz.sync?.groupId;
      if (!plcTemplateSyncGroupId) {
        const newSyncGroupId = crypto.randomUUID();
        try {
          await createSyncedQuizGroup({
            groupId: newSyncGroupId,
            uid: user.uid,
            title: data.title,
            questions: data.questions,
            plcId: plc.id,
            behavior: pickedQuiz.behavior,
          });
          createdSyncGroupId = newSyncGroupId;
          try {
            await attachSyncLinkage(pickedQuiz.id, {
              groupId: newSyncGroupId,
              lastSyncedVersion: 1,
            });
            linkageAttached = true;
            plcTemplateSyncGroupId = newSyncGroupId;
          } catch (linkageErr) {
            // Roll back the freshly-minted self-participant entry so we
            // don't leak a phantom participant pointing at a local
            // library that never recorded the linkage. The empty group
            // doc itself stays (rules disallow client deletes).
            try {
              await callLeaveSyncedQuizGroup(newSyncGroupId);
            } catch (leaveErr) {
              logError(
                'PlcNewQuizAssignmentModal.promoteSync.rollbackLeave',
                leaveErr,
                { plcId: plc.id, syncGroupId: newSyncGroupId }
              );
            }
            // We deliberately don't throw — falling through without a
            // sync group means we skip the PLC template write, but the
            // canonical assignment + assignment_index still commit so
            // the In-progress sub-tab still surfaces the assignment.
            logError(
              'PlcNewQuizAssignmentModal.promoteSync.attachLinkage',
              linkageErr,
              { plcId: plc.id, quizId: pickedQuiz.id }
            );
            plcTemplateSyncGroupId = undefined;
          }
        } catch (createErr) {
          logError('PlcNewQuizAssignmentModal.promoteSync.create', createErr, {
            plcId: plc.id,
            quizId: pickedQuiz.id,
          });
          plcTemplateSyncGroupId = undefined;
        }
      }

      // Task 10: source sessionMode/sessionOptions/attemptLimit from the
      // quiz's behavior settings (getQuizBehavior). No longer driven by
      // removed form controls.
      const behavior = getQuizBehavior(pickedQuiz);
      const sessionOptions: QuizSessionOptions = behavior.sessionOptions;

      const { id: assignmentId } = await createAssignment(
        {
          id: pickedQuiz.id,
          title: pickedQuiz.title,
          driveFileId: pickedQuiz.driveFileId,
          questions: data.questions,
        },
        {
          sessionMode: behavior.sessionMode,
          sessionOptions,
          attemptLimit: behavior.attemptLimit,
          teacherName: options.teacherName.trim() || undefined,
          periodName: derived.periodNames[0],
          periodNames: derived.periodNames,
          plc: plcLinkage,
          ...(dueAt != null ? { dueAt } : {}),
        },
        {
          initialStatus: 'paused',
          classIds: derived.classIds,
          rosterIds: derived.rosterIds,
          classPeriodByClassId: derived.classPeriodByClassId,
          mode: assignmentMode,
          ...(plcTemplateSyncGroupId ? { plcTemplateSyncGroupId } : {}),
        }
      );

      addToast(
        t('plcDashboard.newAssignment.quiz.created', {
          title: pickedQuiz.title,
          defaultValue:
            '"{{title}}" created (paused) and shared with this PLC.',
        }),
        'success'
      );
      onCreated?.({ assignmentId, quizTitle: pickedQuiz.title });
      onClose();
    } catch (err) {
      // The orphaned-group state we can leave behind here is the same one
      // PR #1595 documented for the share picker: createAssignment fails
      // AFTER we've already minted a synced group + attached linkage. The
      // local quiz keeps the linkage; the PLC's template/index stay empty.
      // No `detachSyncLinkage` API exists today; we log + observe.
      if (createdSyncGroupId && linkageAttached) {
        logError(
          'newPlcAssignment.orphanedGroup',
          err instanceof Error ? err : new Error(String(err)),
          {
            plcId: plc.id,
            quizId: pickedQuiz?.id,
            syncGroupId: createdSyncGroupId,
          }
        );
      } else {
        logError(
          'PlcNewQuizAssignmentModal.submit',
          err instanceof Error ? err : new Error(String(err)),
          { plcId: plc.id, quizId: pickedQuiz?.id }
        );
      }
      addToast(
        err instanceof Error
          ? err.message
          : t('plcDashboard.newAssignment.quiz.createFailed', {
              defaultValue: 'Failed to create the PLC assignment.',
            }),
        'error'
      );
    } finally {
      submittingRef.current = false;
      setSubmitting(false);
    }
  }, [
    addToast,
    assignmentMode,
    attachSyncLinkage,
    createAssignment,
    dueAt,
    ensureGoogleScope,
    loadQuizData,
    onClose,
    onCreated,
    options,
    pickedQuiz,
    plc,
    rosters,
    t,
    useAutoGenerated,
    user,
  ]);

  // ─── Step 1: pick from personal library ──────────────────────────────────
  if (step === 'pick') {
    return (
      <PlcSharePickerModal
        title={t('plcDashboard.newAssignment.quiz.pickTitle', {
          defaultValue: 'New PLC Quiz Assignment',
        })}
        subtitle={t('plcDashboard.newAssignment.quiz.pickSubtitle', {
          name: plc.name,
          defaultValue: 'Shared with {{name}}',
        })}
        prompt={
          isDriveConnected
            ? t('plcDashboard.newAssignment.quiz.pickPrompt', {
                defaultValue:
                  'Pick a quiz from your personal library. The assignment will be created paused so you can review it before going live.',
              })
            : t('plcDashboard.newAssignment.quiz.pickPromptNoDrive', {
                defaultValue:
                  'Connect Google Drive in your account to assign quizzes from your personal library.',
              })
        }
        emptyMessage={t('plcDashboard.newAssignment.quiz.pickEmpty', {
          defaultValue:
            "You don't have any quizzes in your personal library yet. Create one in the Quiz widget first.",
        })}
        items={pickerItems}
        onPick={handlePick}
        onClose={onClose}
      />
    );
  }

  // ─── Step 2: slimmed configure — class picker + due-date + behavior summary
  if (!pickedQuiz) {
    // Defensive: callers transition `step` only after `pickedQuiz` is set,
    // so this branch is unreachable in practice. Bail rather than render
    // a broken modal if state ever desynchronizes.
    return null;
  }

  const behavior = getQuizBehavior(pickedQuiz);
  const behaviorSummary = formatBehaviorSummary(behavior);

  const visibleRosterIds = new Set(
    rosters.filter((r) => !r.loadError).map((r) => r.id)
  );
  const effectivePeriodCount = options.picker.rosterIds.filter((id) =>
    visibleRosterIds.has(id)
  ).length;

  const dateInputValue = dueAt
    ? new Date(dueAt).toISOString().slice(0, 10)
    : '';

  const handleDateChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setDueAt(val ? new Date(val).getTime() : null);
  };

  const modalTitle = t('plcDashboard.newAssignment.quiz.configureTitle', {
    title: pickedQuiz.title,
    defaultValue: 'Assign "{{title}}"',
  });

  return (
    <div
      className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4"
      role="dialog"
      aria-modal="true"
      aria-label={modalTitle}
    >
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100">
          <div>
            <h2 className="text-base font-semibold text-slate-900">
              {modalTitle}
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">
              {t('plcDashboard.newAssignment.quiz.configureSubtitle', {
                name: plc.name,
                defaultValue: 'Shared with {{name}}',
              })}
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors"
            aria-label={t('common.close', { defaultValue: 'Close' })}
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-4 space-y-5">
          {/* Class / period picker */}
          <div>
            <p className="text-sm font-medium text-slate-700 mb-2">
              {t('plcDashboard.newAssignment.quiz.classPickerLabel', {
                defaultValue: 'Target class periods (optional)',
              })}
            </p>
            <AssignClassPicker
              rosters={rosters}
              value={options.picker}
              onChange={(picker) => setOptions((p) => ({ ...p, picker }))}
            />
          </div>

          {/* Due date */}
          <div>
            <label
              htmlFor="plc-assign-due-date-input"
              className="block text-sm font-medium text-slate-700 mb-1 flex items-center gap-1.5"
            >
              <Calendar className="w-4 h-4" aria-hidden="true" />
              {t('plcDashboard.newAssignment.quiz.dueDateLabel', {
                defaultValue: 'Due date (optional)',
              })}
            </label>
            <input
              id="plc-assign-due-date-input"
              type="date"
              data-testid="plc-assign-due-date"
              value={dateInputValue}
              onChange={handleDateChange}
              className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-brand-blue-primary/30"
            />
          </div>

          {/* Read-only behavior summary */}
          <div className="bg-slate-50 rounded-xl p-3 border border-slate-100 space-y-1.5">
            <div className="flex items-center justify-between gap-2">
              <p className="text-xxs font-bold text-slate-400 uppercase tracking-widest">
                {t('plcDashboard.newAssignment.quiz.behaviorLabel', {
                  defaultValue: 'Behavior',
                })}
              </p>
              <span className="text-xxs text-slate-400">
                {t('plcDashboard.newAssignment.quiz.behaviorEditHint', {
                  defaultValue: 'Edit in the quiz editor',
                })}
              </span>
            </div>
            <p
              data-testid="plc-quiz-behavior-summary"
              className="text-sm text-slate-600 leading-snug"
            >
              {behaviorSummary}
            </p>
          </div>

          {/* PLC sharing slot (teacher name + auto-sheet toggle) */}
          <PlcNewAssignmentSharingSlot
            plcName={plc.name}
            effectivePeriodCount={effectivePeriodCount}
            teacherName={options.teacherName}
            onTeacherNameChange={(v) =>
              setOptions((p) => ({ ...p, teacherName: v }))
            }
            useAutoGenerated={useAutoGenerated}
            onUseAutoGeneratedChange={(v) => {
              setUseAutoGenerated(v);
              if (v) setOptions((p) => ({ ...p, plcSheetUrl: '' }));
            }}
            plcSheetUrl={options.plcSheetUrl}
            onPlcSheetUrlChange={(v) =>
              setOptions((p) => ({ ...p, plcSheetUrl: v }))
            }
            plcSheetUrlInvalid={plcSheetUrlInvalid}
            googleAccessToken={googleAccessToken}
          />
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-slate-100">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-lg text-sm font-medium text-slate-600 hover:bg-slate-100 transition-colors"
          >
            {t('common.cancel', { defaultValue: 'Cancel' })}
          </button>
          <button
            type="button"
            onClick={() => void handleSubmit()}
            disabled={submitting || plcSheetUrlInvalid}
            title={
              plcSheetUrlInvalid
                ? t('plcDashboard.newAssignment.sharing.sheetUrlInvalid', {
                    defaultValue: "This doesn't look like a Google Sheets URL.",
                  })
                : undefined
            }
            className="px-4 py-2 rounded-lg bg-brand-blue-primary text-white text-sm font-semibold hover:bg-brand-blue-dark transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {submitting
              ? t('plcDashboard.assignmentConfig.creating', {
                  defaultValue: 'Creating…',
                })
              : t('plcDashboard.newAssignment.confirm', {
                  defaultValue: 'Create assignment',
                })}
          </button>
        </div>
      </div>
    </div>
  );
};
