/**
 * PlcNewAssignmentSharingSlot — the "Sharing with **{PLC name}**" block
 * shared by `PlcNewQuizAssignmentModal` and
 * `PlcNewVideoActivityAssignmentModal`. Both wizards inlined the same
 * ~115-line plcSlot before this extraction; consolidating here so a
 * tweak to the layout / copy / auto-sheet toggle lands in one place.
 *
 * Presentational + controlled — the parent owns every field's state and
 * passes the values + change handlers in. The slot has no PLC picker
 * because both wizards run inside a fixed PLC dashboard.
 */

import React, { useId } from 'react';
import { useTranslation } from 'react-i18next';
import { AlertTriangle, Share2 } from 'lucide-react';
import { ToggleRow } from '@/components/common/library/AssignmentSettingsToggleGroup';

interface PlcNewAssignmentSharingSlotProps {
  plcName: string;
  /**
   * Number of class-period labels the picker is contributing. Drives the
   * "students will see a picker" hint copy. Pass `0` when no rosters
   * have been selected yet.
   */
  effectivePeriodCount: number;
  teacherName: string;
  onTeacherNameChange: (next: string) => void;
  useAutoGenerated: boolean;
  onUseAutoGeneratedChange: (next: boolean) => void;
  plcSheetUrl: string;
  onPlcSheetUrlChange: (next: string) => void;
  /** True iff the user typed a manual URL that isn't a Google Sheets URL. */
  plcSheetUrlInvalid: boolean;
  /**
   * Truthy iff the user is signed into Google (and so the auto-create
   * branch can actually mint a sheet). When falsy AND the toggle is ON,
   * surfaces an amber hint that the assignment will be created without a
   * sheet attached.
   */
  googleAccessToken: string | null;
}

export const PlcNewAssignmentSharingSlot: React.FC<
  PlcNewAssignmentSharingSlotProps
> = ({
  plcName,
  effectivePeriodCount,
  teacherName,
  onTeacherNameChange,
  useAutoGenerated,
  onUseAutoGeneratedChange,
  plcSheetUrl,
  onPlcSheetUrlChange,
  plcSheetUrlInvalid,
  googleAccessToken,
}) => {
  const { t } = useTranslation();
  // Stable ids so the visible `<label>` elements (which are siblings of
  // their `<input>` controls, not wrappers, because of the row layout)
  // associate properly for screen readers. Without these, AT announces
  // each input as bare "edit, blank" with no semantic role.
  const teacherNameId = useId();
  const sheetUrlId = useId();

  return (
    <div className="border-t border-slate-200/70 pt-3 space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Share2 className="w-4 h-4 text-brand-blue-primary" />
          <span className="text-sm font-bold text-brand-blue-dark">
            {t('plcDashboard.newAssignment.sharing.heading', {
              name: plcName,
              defaultValue: 'Sharing with {{name}}',
            })}
          </span>
        </div>
        <span className="text-xxs font-bold uppercase tracking-wider text-emerald-700 bg-emerald-100 rounded-full px-2 py-0.5">
          {t('plcDashboard.newAssignment.sharing.plcMode', {
            defaultValue: 'PLC mode',
          })}
        </span>
      </div>
      <p className="text-xxs text-slate-500 -mt-1">
        {effectivePeriodCount > 1
          ? t('plcDashboard.newAssignment.sharing.periodPickerHint', {
              defaultValue:
                'Students will see a class-period picker after entering their PIN.',
            })
          : t('plcDashboard.newAssignment.sharing.singleClassHint', {
              defaultValue:
                'Pick two or more classes above to give students a period picker when they join.',
            })}
      </p>
      <div className="space-y-3 bg-slate-50 rounded-xl p-3 border border-slate-100">
        <div>
          <label
            htmlFor={teacherNameId}
            className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1"
          >
            {t('plcDashboard.newAssignment.sharing.teacherNameLabel', {
              defaultValue: 'Your Name',
            })}
          </label>
          <input
            id={teacherNameId}
            type="text"
            value={teacherName}
            onChange={(e) => onTeacherNameChange(e.target.value)}
            placeholder={t(
              'plcDashboard.newAssignment.sharing.teacherNamePlaceholder',
              { defaultValue: 'e.g. Ms. Smith' }
            )}
            className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-brand-blue-primary"
          />
          <p className="text-xxs text-slate-400 mt-0.5">
            {t('plcDashboard.newAssignment.sharing.teacherNameHint', {
              defaultValue:
                'Appears in the "Teacher" column of the shared sheet.',
            })}
          </p>
        </div>
        <ToggleRow
          label={t('plcDashboard.newAssignment.sharing.autoSheetLabel', {
            defaultValue: 'Auto-Generated PLC Sheet',
          })}
          checked={useAutoGenerated}
          onChange={(v) => {
            onUseAutoGeneratedChange(v);
            // Caller is also responsible for any side-effect on toggle
            // (e.g. clearing `plcSheetUrl` on flip-to-auto); we don't
            // change parent state here beyond the toggle itself so the
            // slot stays presentational.
          }}
          hint={
            useAutoGenerated
              ? t('plcDashboard.newAssignment.sharing.autoSheetHintOn', {
                  defaultValue:
                    'SpartBoard creates a fresh Google Sheet for this assignment and shares it with your PLC.',
                })
              : t('plcDashboard.newAssignment.sharing.autoSheetHintOff', {
                  defaultValue:
                    'Paste a Google Sheet URL — useful for pointing this assignment at a sheet you already have.',
                })
          }
        />
        {!useAutoGenerated && (
          <div>
            <label
              htmlFor={sheetUrlId}
              className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1"
            >
              {t('plcDashboard.newAssignment.sharing.sheetUrlLabel', {
                defaultValue: 'Shared Google Sheet URL',
              })}
            </label>
            <input
              id={sheetUrlId}
              type="text"
              value={plcSheetUrl}
              onChange={(e) => onPlcSheetUrlChange(e.target.value)}
              placeholder={t(
                'plcDashboard.newAssignment.sharing.sheetUrlPlaceholder',
                { defaultValue: 'https://docs.google.com/spreadsheets/d/...' }
              )}
              className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-brand-blue-primary"
            />
            {plcSheetUrlInvalid && (
              <div className="flex items-center gap-1 mt-1 text-amber-600">
                <AlertTriangle className="w-3 h-3" />
                <span className="text-xxs">
                  {t('plcDashboard.newAssignment.sharing.sheetUrlInvalid', {
                    defaultValue: "This doesn't look like a Google Sheets URL.",
                  })}
                </span>
              </div>
            )}
          </div>
        )}
        {useAutoGenerated && !googleAccessToken && (
          <p className="text-xxs text-amber-700 bg-amber-50 border border-amber-200 rounded-md px-2 py-1.5">
            {t('plcDashboard.newAssignment.sharing.driveDisconnectedHint', {
              defaultValue:
                "You're not signed into Google — the assignment will be created without a PLC sheet attached. Reconnect Drive and edit the assignment to add one.",
            })}
          </p>
        )}
      </div>
    </div>
  );
};
