/**
 * PlcNewQuizAssignmentModal — in-tab "+ Assign Quiz" wizard for the PLC
 * dashboard's Assignments → Library sub-tab.
 *
 * Two-step flow:
 *
 *   1. Pick a quiz from the teacher's personal library
 *      (reuses `PlcSharePickerModal`).
 *   2. Configure the full assignment in `AssignModal` chrome with the
 *      same extras the QuizWidget's kebab-driven assign flow uses
 *      (mode picker, integrity / randomization / feedback toggles, attempt
 *      limit, gamification). The PLC slot is replaced with a simplified
 *      "Sharing with **this PLC**" block — no PLC picker because the
 *      target PLC is fixed.
 *
 * On submit, mirrors `QuizWidget.handleAssignConfirm` (the kebab path):
 *
 *   a. Auto-create a PLC sheet if Drive is connected and no manual URL
 *      was provided.
 *   b. Resolve the `PlcLinkage` sub-object (id, name, sheetUrl,
 *      memberEmails, autoGenerated).
 *   c. If the source quiz has no `sync.groupId`, mint one with
 *      `plcId` set (so PLC-aware tooling can find it), attach the sync
 *      linkage to the local quiz, and pass the new id through as
 *      `plcTemplateSyncGroupId`. This is what lets teammates who later
 *      "Add to my board" land on the same canonical content.
 *   d. `createAssignment` with `settings.plc` set — the hook handles the
 *      `assignment_index` entry (`kind: 'quiz'`) AND the
 *      `assignments` template write, so the In-progress sub-tab picks
 *      up the new row via its live snapshot.
 *
 * Known orphan-group gap: if step (d) fails after step (c) succeeded the
 * personal copy retains a self-only sync linkage and the PLC's
 * `assignment_index` / template stay empty. There's no
 * `detachSyncLinkage` API today, so we log under
 * `newPlcAssignment.orphanedGroup` for observability and surface a toast.
 * Same posture PR #1595 took for the share picker.
 */

import React, { useCallback, useMemo, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { AlertTriangle, Clock, Share2, User, Zap } from 'lucide-react';
import type {
  AssignmentMode,
  ClassRoster,
  Plc,
  PlcLinkage,
  QuizMetadata,
  QuizSessionMode,
  QuizSessionOptions,
} from '@/types';
import { useAuth } from '@/context/useAuth';
import { useDashboard } from '@/context/useDashboard';
import { useQuiz } from '@/hooks/useQuiz';
import { useQuizAssignments } from '@/hooks/useQuizAssignments';
import {
  callLeaveSyncedQuizGroup,
  createSyncedQuizGroup,
} from '@/hooks/useSyncedQuizGroups';
import { getPlcMemberEmails, getPlcTeammateEmails } from '@/utils/plc';
import { QuizDriveService } from '@/utils/quizDriveService';
import { deriveSessionTargetsFromRosters } from '@/utils/resolveAssignmentTargets';
import { logError } from '@/utils/logError';
import { AssignModal } from '@/components/common/library/AssignModal';
import { AssignClassPicker } from '@/components/common/AssignClassPicker';
import {
  makeEmptyPickerValue,
  type AssignClassPickerValue,
} from '@/components/common/AssignClassPicker.helpers';
import {
  AssignmentSettingsToggleGroup,
  ToggleRow,
} from '@/components/common/library/AssignmentSettingsToggleGroup';
import { CollapsibleSection } from '@/components/common/library/CollapsibleSection';
import type { AssignModeOption } from '@/components/common/library/types';
import {
  PlcSharePickerModal,
  type PlcSharePickerItem,
} from './PlcSharePickerModal';

interface PlcNewQuizAssignmentModalProps {
  plc: Plc;
  /**
   * Org-wide assignment mode frozen onto the new assignment + session.
   * Defaults to `'submissions'`. The PLC dashboard reads it from the
   * authenticated teacher's `appSettings` and forwards it here so the
   * new assignment matches every other assignment created in this org.
   */
  assignmentMode?: AssignmentMode;
  onClose: () => void;
  /**
   * Fired after the assignment write + index write commit. The parent
   * uses this to surface a follow-up toast and to optionally chain
   * straight into the post-create "Edit all settings…" hand-off.
   */
  onCreated?: (info: { assignmentId: string; quizTitle: string }) => void;
}

const QUIZ_MODES: AssignModeOption[] = [
  {
    id: 'teacher',
    label: 'Teacher-paced',
    description: 'You control when to move to the next question.',
    icon: User,
  },
  {
    id: 'auto',
    label: 'Auto-progress',
    description: 'Moves automatically once everyone has answered.',
    icon: Zap,
  },
  {
    id: 'student',
    label: 'Self-paced',
    description: 'Students move through questions at their own speed.',
    icon: Clock,
  },
];

interface QuizAssignOptions {
  tabWarningsEnabled: boolean;
  showResultToStudent: boolean;
  showCorrectAnswerToStudent: boolean;
  showCorrectOnBoard: boolean;
  speedBonusEnabled: boolean;
  streakBonusEnabled: boolean;
  showPodiumBetweenQuestions: boolean;
  soundEffectsEnabled: boolean;
  shuffleQuestions: boolean;
  shuffleAnswerOptions: boolean;
  attemptLimit: number | null;
  teacherName: string;
  plcSheetUrl: string;
  picker: AssignClassPickerValue;
}

function buildDefaultOptions(defaultTeacherName?: string): QuizAssignOptions {
  return {
    tabWarningsEnabled: true,
    showResultToStudent: false,
    showCorrectAnswerToStudent: false,
    showCorrectOnBoard: false,
    speedBonusEnabled: false,
    streakBonusEnabled: false,
    showPodiumBetweenQuestions: false,
    soundEffectsEnabled: false,
    shuffleQuestions: false,
    shuffleAnswerOptions: true,
    attemptLimit: 1,
    teacherName: defaultTeacherName ?? '',
    plcSheetUrl: '',
    picker: makeEmptyPickerValue(),
  };
}

function formatRelativeDate(ms: number): string {
  try {
    return new Date(ms).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  } catch {
    return '';
  }
}

export const PlcNewQuizAssignmentModal: React.FC<
  PlcNewQuizAssignmentModalProps
> = ({ plc, assignmentMode = 'submissions', onClose, onCreated }) => {
  const { t } = useTranslation();
  const { user, googleAccessToken } = useAuth();
  const { addToast, rosters } = useDashboard();
  const { quizzes, loadQuizData, attachSyncLinkage, isDriveConnected } =
    useQuiz(user?.uid);
  const { createAssignment } = useQuizAssignments(user?.uid);

  const [step, setStep] = useState<'pick' | 'configure'>('pick');
  const [pickedQuiz, setPickedQuiz] = useState<QuizMetadata | null>(null);
  const [selectedMode, setSelectedMode] = useState<QuizSessionMode | null>(
    null
  );
  const [options, setOptions] = useState<QuizAssignOptions>(() =>
    buildDefaultOptions(user?.displayName ?? undefined)
  );
  // Auto-Generated PLC Sheet toggle: ON by default; flipping OFF reveals
  // the manual-URL field. Mirrors the QuizWidget AssignPlcSlot behavior.
  const [useAutoGenerated, setUseAutoGenerated] = useState(true);
  // Synchronous submit guard. State alone isn't enough — a double-click
  // can fire two submit handlers before React commits the first
  // setState. See `PlcSharePickerModal.handlePick` for the same pattern.
  const submittingRef = useRef(false);

  const pickerItems: PlcSharePickerItem[] = useMemo(
    () =>
      quizzes.map((quiz) => ({
        id: quiz.id,
        title: quiz.title,
        metaLine: t('plcDashboard.newAssignment.quiz.metaLine', {
          count: quiz.questionCount ?? 0,
          date: formatRelativeDate(quiz.updatedAt ?? quiz.createdAt ?? 0),
          defaultValue: '{{count}} questions · {{date}}',
        }),
      })),
    [quizzes, t]
  );

  const plcSheetUrlInvalid =
    !useAutoGenerated &&
    !!options.plcSheetUrl.trim() &&
    !options.plcSheetUrl
      .trim()
      .startsWith('https://docs.google.com/spreadsheets/');

  const handlePick = useCallback(
    (quizId: string): Promise<void> => {
      const meta = quizzes.find((q) => q.id === quizId);
      if (!meta) {
        addToast(
          t('plcDashboard.newAssignment.quiz.missingFromLibrary', {
            defaultValue: 'That quiz is no longer in your library.',
          }),
          'error'
        );
        return Promise.resolve();
      }
      setPickedQuiz(meta);
      setStep('configure');
      return Promise.resolve();
    },
    [addToast, quizzes, t]
  );

  const handleSubmit = useCallback(async () => {
    if (submittingRef.current) return;
    if (!pickedQuiz || !selectedMode || !user) return;
    submittingRef.current = true;

    let createdSyncGroupId: string | null = null;
    let linkageAttached = false;
    try {
      // Load Drive content up front so a sync-group mint never lands
      // without questions, and so any Drive auth issue surfaces a toast
      // before we touch shared state.
      const data = await loadQuizData(pickedQuiz.driveFileId);

      const visibleRosterIds = new Set(
        rosters.filter((r) => !r.loadError).map((r) => r.id)
      );
      const validRosterIds = options.picker.rosterIds.filter((id) =>
        visibleRosterIds.has(id)
      );
      const selectedRosters: ClassRoster[] = rosters.filter((r) =>
        validRosterIds.includes(r.id)
      );
      const derived = deriveSessionTargetsFromRosters(selectedRosters);

      // PLC sheet resolution: auto-create when the toggle is ON and no
      // manual URL was provided. Mirrors `QuizWidget.handleAssignConfirm`
      // — best-effort, toasts on failure, falls through to "no sheet
      // attached" rather than blocking the assignment.
      const trimmedManualUrl = options.plcSheetUrl.trim();
      let resolvedSheetUrl = useAutoGenerated ? '' : trimmedManualUrl;
      let sheetAutoGenerated = false;
      if (useAutoGenerated && !resolvedSheetUrl && googleAccessToken) {
        try {
          const driveService = new QuizDriveService(googleAccessToken);
          const created = await driveService.createPlcSheetAndShare({
            plcName: plc.name,
            quizTitle: pickedQuiz.title,
            memberEmailsToShareWith: getPlcTeammateEmails(plc, user.uid),
          });
          resolvedSheetUrl = created.url;
          sheetAutoGenerated = true;
        } catch (err) {
          logError('PlcNewQuizAssignmentModal.sheetAutoCreate', err, {
            plcId: plc.id,
            quizId: pickedQuiz.id,
          });
          addToast(
            err instanceof Error && err.message
              ? err.message
              : t('plcDashboard.newAssignment.quiz.sheetAutoCreateFailed', {
                  defaultValue:
                    'Could not create the shared PLC sheet — you can still paste a URL manually, or save without a sheet.',
                }),
            'error'
          );
        }
      }

      const plcLinkage: PlcLinkage = {
        id: plc.id,
        name: plc.name,
        sheetUrl: resolvedSheetUrl,
        memberEmails: getPlcMemberEmails(plc),
        ...(sheetAutoGenerated ? { autoGenerated: true } : {}),
      };

      // Promote-to-synced: if the source quiz has no `sync.groupId`,
      // mint one with `plcId` set so peer importers landing on the PLC
      // template can read the canonical group. Mirrors the QuizWidget
      // `plcLinkage && !plcTemplateSyncGroupId` branch.
      let plcTemplateSyncGroupId: string | undefined = pickedQuiz.sync?.groupId;
      if (!plcTemplateSyncGroupId) {
        const newSyncGroupId = crypto.randomUUID();
        try {
          await createSyncedQuizGroup({
            groupId: newSyncGroupId,
            uid: user.uid,
            title: data.title,
            questions: data.questions,
            plcId: plc.id,
          });
          createdSyncGroupId = newSyncGroupId;
          try {
            await attachSyncLinkage(pickedQuiz.id, {
              groupId: newSyncGroupId,
              lastSyncedVersion: 1,
            });
            linkageAttached = true;
            plcTemplateSyncGroupId = newSyncGroupId;
          } catch (linkageErr) {
            // Roll back the freshly-minted self-participant entry so we
            // don't leak a phantom participant pointing at a local
            // library that never recorded the linkage. The empty group
            // doc itself stays (rules disallow client deletes).
            try {
              await callLeaveSyncedQuizGroup(newSyncGroupId);
            } catch (leaveErr) {
              logError(
                'PlcNewQuizAssignmentModal.promoteSync.rollbackLeave',
                leaveErr,
                { plcId: plc.id, syncGroupId: newSyncGroupId }
              );
            }
            // We deliberately don't throw — falling through without a
            // sync group means we skip the PLC template write, but the
            // canonical assignment + assignment_index still commit so
            // the In-progress sub-tab still surfaces the assignment.
            logError(
              'PlcNewQuizAssignmentModal.promoteSync.attachLinkage',
              linkageErr,
              { plcId: plc.id, quizId: pickedQuiz.id }
            );
            plcTemplateSyncGroupId = undefined;
          }
        } catch (createErr) {
          logError('PlcNewQuizAssignmentModal.promoteSync.create', createErr, {
            plcId: plc.id,
            quizId: pickedQuiz.id,
          });
          plcTemplateSyncGroupId = undefined;
        }
      }

      const sessionOptions: QuizSessionOptions = {
        tabWarningsEnabled: options.tabWarningsEnabled,
        showResultToStudent: options.showResultToStudent,
        showCorrectAnswerToStudent: options.showCorrectAnswerToStudent,
        showCorrectOnBoard: options.showCorrectOnBoard,
        speedBonusEnabled: options.speedBonusEnabled,
        streakBonusEnabled: options.streakBonusEnabled,
        showPodiumBetweenQuestions: options.showPodiumBetweenQuestions,
        soundEffectsEnabled: options.soundEffectsEnabled,
        shuffleQuestions: options.shuffleQuestions,
        shuffleAnswerOptions: options.shuffleAnswerOptions,
      };

      const { id: assignmentId } = await createAssignment(
        {
          id: pickedQuiz.id,
          title: pickedQuiz.title,
          driveFileId: pickedQuiz.driveFileId,
          questions: data.questions,
        },
        {
          sessionMode: selectedMode,
          sessionOptions,
          attemptLimit: options.attemptLimit,
          teacherName: options.teacherName.trim() || undefined,
          periodName: derived.periodNames[0],
          periodNames: derived.periodNames,
          plc: plcLinkage,
        },
        {
          initialStatus: 'paused',
          classIds: derived.classIds,
          rosterIds: derived.rosterIds,
          classPeriodByClassId: derived.classPeriodByClassId,
          mode: assignmentMode,
          ...(plcTemplateSyncGroupId ? { plcTemplateSyncGroupId } : {}),
        }
      );

      addToast(
        t('plcDashboard.newAssignment.quiz.created', {
          title: pickedQuiz.title,
          defaultValue:
            '"{{title}}" created (paused) and shared with this PLC.',
        }),
        'success'
      );
      onCreated?.({ assignmentId, quizTitle: pickedQuiz.title });
      onClose();
    } catch (err) {
      // The orphaned-group state we can leave behind here is the same one
      // PR #1595 documented for the share picker: createAssignment fails
      // AFTER we've already minted a synced group + attached linkage. The
      // local quiz keeps the linkage; the PLC's template/index stay empty.
      // No `detachSyncLinkage` API exists today; we log + observe.
      if (createdSyncGroupId && linkageAttached) {
        logError(
          'newPlcAssignment.orphanedGroup',
          err instanceof Error ? err : new Error(String(err)),
          {
            plcId: plc.id,
            quizId: pickedQuiz?.id,
            syncGroupId: createdSyncGroupId,
          }
        );
      } else {
        logError(
          'PlcNewQuizAssignmentModal.submit',
          err instanceof Error ? err : new Error(String(err)),
          { plcId: plc.id, quizId: pickedQuiz?.id }
        );
      }
      addToast(
        err instanceof Error
          ? err.message
          : t('plcDashboard.newAssignment.quiz.createFailed', {
              defaultValue: 'Failed to create the PLC assignment.',
            }),
        'error'
      );
    } finally {
      submittingRef.current = false;
    }
  }, [
    addToast,
    assignmentMode,
    attachSyncLinkage,
    createAssignment,
    googleAccessToken,
    loadQuizData,
    onClose,
    onCreated,
    options,
    pickedQuiz,
    plc,
    rosters,
    selectedMode,
    t,
    useAutoGenerated,
    user,
  ]);

  // ─── Step 1: pick from personal library ──────────────────────────────────
  if (step === 'pick') {
    return (
      <PlcSharePickerModal
        title={t('plcDashboard.newAssignment.quiz.pickTitle', {
          defaultValue: 'New PLC Quiz Assignment',
        })}
        subtitle={t('plcDashboard.newAssignment.quiz.pickSubtitle', {
          name: plc.name,
          defaultValue: 'Shared with {{name}}',
        })}
        prompt={
          isDriveConnected
            ? t('plcDashboard.newAssignment.quiz.pickPrompt', {
                defaultValue:
                  'Pick a quiz from your personal library. The assignment will be created paused so you can review it before going live.',
              })
            : t('plcDashboard.newAssignment.quiz.pickPromptNoDrive', {
                defaultValue:
                  'Connect Google Drive in your account to assign quizzes from your personal library.',
              })
        }
        emptyMessage={t('plcDashboard.newAssignment.quiz.pickEmpty', {
          defaultValue:
            "You don't have any quizzes in your personal library yet. Create one in the Quiz widget first.",
        })}
        items={pickerItems}
        onPick={handlePick}
        onClose={onClose}
      />
    );
  }

  // ─── Step 2: full settings via AssignModal chrome ────────────────────────
  if (!pickedQuiz) {
    // Defensive: callers transition `step` only after `pickedQuiz` is set,
    // so this branch is unreachable in practice. Bail rather than render
    // an empty AssignModal if state ever desynchronizes.
    return null;
  }

  const visibleRosterIds = new Set(
    rosters.filter((r) => !r.loadError).map((r) => r.id)
  );
  const effectivePeriodCount = options.picker.rosterIds.filter((id) =>
    visibleRosterIds.has(id)
  ).length;

  return (
    <AssignModal<QuizAssignOptions>
      isOpen
      onClose={onClose}
      itemTitle={pickedQuiz.title}
      modes={QUIZ_MODES}
      selectedMode={selectedMode ?? undefined}
      onModeChange={(id) => setSelectedMode(id as QuizSessionMode)}
      options={options}
      onOptionsChange={setOptions}
      extraSlot={
        <>
          <AssignClassPicker
            rosters={rosters}
            value={options.picker}
            onChange={(picker) => setOptions((p) => ({ ...p, picker }))}
          />
          <AssignmentSettingsToggleGroup
            options={{
              tabWarningsEnabled: options.tabWarningsEnabled,
              showResultToStudent: options.showResultToStudent,
              showCorrectAnswerToStudent: options.showCorrectAnswerToStudent,
              showCorrectOnBoard: options.showCorrectOnBoard,
              shuffleQuestions: options.shuffleQuestions,
              shuffleAnswerOptions: options.shuffleAnswerOptions,
            }}
            onOptionsChange={(next) => setOptions((p) => ({ ...p, ...next }))}
            attemptLimit={options.attemptLimit}
            onAttemptLimitChange={(v) =>
              setOptions((p) => ({ ...p, attemptLimit: v }))
            }
            // Shuffle Questions only fires in self-paced mode (the only
            // mode that broadcasts per-student question sequences). The
            // primitive renders a "self-paced only" hint when disabled.
            shuffleQuestionsAvailable={selectedMode === 'student'}
            trailingSlot={
              <CollapsibleSection label="Gamification">
                <ToggleRow
                  compact
                  label="Speed Bonus Points"
                  checked={options.speedBonusEnabled}
                  onChange={(v) =>
                    setOptions((p) => ({ ...p, speedBonusEnabled: v }))
                  }
                  hint="Up to 50% bonus for fast answers"
                />
                <ToggleRow
                  compact
                  label="Streak Bonuses"
                  checked={options.streakBonusEnabled}
                  onChange={(v) =>
                    setOptions((p) => ({ ...p, streakBonusEnabled: v }))
                  }
                  hint="Multiplier for consecutive correct answers"
                />
                <ToggleRow
                  compact
                  label="Podium Between Questions"
                  checked={options.showPodiumBetweenQuestions}
                  onChange={(v) =>
                    setOptions((p) => ({
                      ...p,
                      showPodiumBetweenQuestions: v,
                    }))
                  }
                  hint="Show top 3 leaderboard after each question"
                />
                <ToggleRow
                  compact
                  label="Sound Effects"
                  checked={options.soundEffectsEnabled}
                  onChange={(v) =>
                    setOptions((p) => ({ ...p, soundEffectsEnabled: v }))
                  }
                  hint="Chimes, ticks, and fanfares during the quiz"
                />
              </CollapsibleSection>
            }
          />
        </>
      }
      plcSlot={
        <div className="border-t border-slate-200/70 pt-3 space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Share2 className="w-4 h-4 text-brand-blue-primary" />
              <span className="text-sm font-bold text-brand-blue-dark">
                {t('plcDashboard.newAssignment.sharing.heading', {
                  name: plc.name,
                  defaultValue: 'Sharing with {{name}}',
                })}
              </span>
            </div>
            <span className="text-xxs font-bold uppercase tracking-wider text-emerald-700 bg-emerald-100 rounded-full px-2 py-0.5">
              {t('plcDashboard.newAssignment.sharing.plcMode', {
                defaultValue: 'PLC mode',
              })}
            </span>
          </div>
          <p className="text-xxs text-slate-500 -mt-1">
            {effectivePeriodCount > 1
              ? t('plcDashboard.newAssignment.sharing.periodPickerHint', {
                  defaultValue:
                    'Students will see a class-period picker after entering their PIN.',
                })
              : t('plcDashboard.newAssignment.sharing.singleClassHint', {
                  defaultValue:
                    'Pick two or more classes above to give students a period picker when they join.',
                })}
          </p>
          <div className="space-y-3 bg-slate-50 rounded-xl p-3 border border-slate-100">
            <div>
              <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
                {t('plcDashboard.newAssignment.sharing.teacherNameLabel', {
                  defaultValue: 'Your Name',
                })}
              </label>
              <input
                type="text"
                value={options.teacherName}
                onChange={(e) =>
                  setOptions((p) => ({ ...p, teacherName: e.target.value }))
                }
                placeholder={t(
                  'plcDashboard.newAssignment.sharing.teacherNamePlaceholder',
                  { defaultValue: 'e.g. Ms. Smith' }
                )}
                className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-brand-blue-primary"
              />
              <p className="text-xxs text-slate-400 mt-0.5">
                {t('plcDashboard.newAssignment.sharing.teacherNameHint', {
                  defaultValue:
                    'Appears in the "Teacher" column of the shared sheet.',
                })}
              </p>
            </div>
            <ToggleRow
              label={t('plcDashboard.newAssignment.sharing.autoSheetLabel', {
                defaultValue: 'Auto-Generated PLC Sheet',
              })}
              checked={useAutoGenerated}
              onChange={(v) => {
                setUseAutoGenerated(v);
                if (v) setOptions((p) => ({ ...p, plcSheetUrl: '' }));
              }}
              hint={
                useAutoGenerated
                  ? t('plcDashboard.newAssignment.sharing.autoSheetHintOn', {
                      defaultValue:
                        'SpartBoard creates a fresh Google Sheet for this assignment and shares it with your PLC.',
                    })
                  : t('plcDashboard.newAssignment.sharing.autoSheetHintOff', {
                      defaultValue:
                        'Paste a Google Sheet URL — useful for pointing this assignment at a sheet you already have.',
                    })
              }
            />
            {!useAutoGenerated && (
              <div>
                <label className="block text-xxs font-bold text-slate-400 uppercase tracking-widest mb-1">
                  {t('plcDashboard.newAssignment.sharing.sheetUrlLabel', {
                    defaultValue: 'Shared Google Sheet URL',
                  })}
                </label>
                <input
                  type="text"
                  value={options.plcSheetUrl}
                  onChange={(e) =>
                    setOptions((p) => ({ ...p, plcSheetUrl: e.target.value }))
                  }
                  placeholder="https://docs.google.com/spreadsheets/d/..."
                  className="w-full px-3 py-2 bg-white border border-slate-200 rounded-lg text-slate-800 text-sm focus:outline-none focus:ring-2 focus:ring-brand-blue-primary"
                />
                {plcSheetUrlInvalid && (
                  <div className="flex items-center gap-1 mt-1 text-amber-600">
                    <AlertTriangle className="w-3 h-3" />
                    <span className="text-xxs">
                      {t('plcDashboard.newAssignment.sharing.sheetUrlInvalid', {
                        defaultValue:
                          "This doesn't look like a Google Sheets URL.",
                      })}
                    </span>
                  </div>
                )}
              </div>
            )}
            {useAutoGenerated && !googleAccessToken && (
              <p className="text-xxs text-amber-700 bg-amber-50 border border-amber-200 rounded-md px-2 py-1.5">
                {t('plcDashboard.newAssignment.sharing.driveDisconnectedHint', {
                  defaultValue:
                    "You're not signed into Google — the assignment will be created without a PLC sheet attached. Reconnect Drive and edit the assignment to add one.",
                })}
              </p>
            )}
          </div>
        </div>
      }
      onAssign={async () => {
        await handleSubmit();
      }}
      confirmLabel={t('plcDashboard.newAssignment.confirm', {
        defaultValue: 'Create assignment',
      })}
      confirmDisabled={!selectedMode || plcSheetUrlInvalid}
      confirmDisabledReason={
        !selectedMode
          ? t('plcDashboard.newAssignment.quiz.modeRequired', {
              defaultValue: 'Choose a session mode first.',
            })
          : t('plcDashboard.newAssignment.sharing.sheetUrlInvalid', {
              defaultValue: "This doesn't look like a Google Sheets URL.",
            })
      }
    />
  );
};
