// LTI 1.3 tool signing-key generator.
//
// Generates an RS256 keypair for the Schoology LTI tool:
//   • Private key (PKCS8 PEM) -> written to the OS temp dir ONLY. Never committed.
//     Upload it to Secret Manager as secret LTI_TOOL_PRIVATE_KEY (see below).
//   • Public key (JWK) -> written into functions/src/lti/toolJwks.ts (safe to commit).
//
// Usage:
//   node scripts/lti-keygen.mjs [kid]
//
// After running, create/rotate the secret (the script prints PEM_PATH):
//   gcloud secrets create LTI_TOOL_PRIVATE_KEY --project=spartboard \
//     --replication-policy=automatic --data-file="<PEM_PATH>"
//   # rotation: gcloud secrets versions add LTI_TOOL_PRIVATE_KEY --data-file="<PEM_PATH>"
//
// Rotation: run with a NEW kid, add a new secret version, and APPEND the new JWK
// to TOOL_PUBLIC_JWKS (keep the old key until all in-flight signed JWTs expire).

import { generateKeyPairSync } from 'node:crypto';
import { writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const kid = process.argv[2] || 'spartboard-lti-2026-06';

const { publicKey, privateKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
});

const privatePem = privateKey.export({ type: 'pkcs8', format: 'pem' });
const jwk = publicKey.export({ format: 'jwk' }); // { kty, n, e }
const publicJwk = {
  kty: jwk.kty,
  n: jwk.n,
  e: jwk.e,
  use: 'sig',
  alg: 'RS256',
  kid,
};

// Private key -> OS temp dir (NOT the repo).
const pemPath = join(tmpdir(), 'lti_tool_private.pem');
writeFileSync(pemPath, privatePem, { encoding: 'utf8' });

// Public JWK -> committed TypeScript module under functions/src/lti.
const ltiDir = join(process.cwd(), 'functions', 'src', 'lti');
mkdirSync(ltiDir, { recursive: true });

const moduleSource = `// AUTO-GENERATED by scripts/lti-keygen.mjs — PUBLIC key material only (safe to commit).
// The matching private key lives in Secret Manager secret LTI_TOOL_PRIVATE_KEY.
// Served at https://spartboard.web.app/.well-known/jwks.json by the ltiJwks function.
//
// Rotation: re-run \`node scripts/lti-keygen.mjs <new-kid>\`, add a new secret version,
// and APPEND the new key to the \`keys\` array (keep old keys until in-flight JWTs expire).

export interface ToolPublicJwk {
  kty: string;
  n: string;
  e: string;
  use: 'sig';
  alg: 'RS256';
  kid: string;
}

/** kid the signing functions stamp into the JWT header (current/active key). */
export const TOOL_SIGNING_KID = '${kid}';

/** Public JWK Set published at /.well-known/jwks.json for Schoology to verify our JWTs. */
export const TOOL_PUBLIC_JWKS: { keys: ToolPublicJwk[] } = {
  keys: [${JSON.stringify(publicJwk)}],
};
`;

writeFileSync(join(ltiDir, 'toolJwks.ts'), moduleSource, { encoding: 'utf8' });

console.log('KID=' + kid);
console.log('PEM_PATH=' + pemPath);
console.log('WROTE=functions/src/lti/toolJwks.ts');
