// Sparty's sprite data: 32×32 grids, one palette character per pixel ('.' is transparent).

export const SPARTY_GRID = 32;

export const SPARTY_PALETTE = {
  B: '#2d3f89', // brand blue (O border)
  N: '#3a4e93', // navy light
  R: '#e8665a', // red light
  Y: '#f8dc86', // gold light
  b: '#b98420', // gold shade
  d: '#8e211c', // red shadow
  k: '#dcab7e', // skin shade
  n: '#1f2e63', // navy
  o: '#1c1c24', // outline and eyes
  r: '#cf3a32', // crest and cape red
  s: '#f3d6b3', // skin
  t: '#6b4423', // spear shaft
  w: '#ffffff', // white
  y: '#ecbb3f', // gold
} as const;

export type SpartyColor = keyof typeof SPARTY_PALETTE;

export const SPARTY_POSE_IDS = [
  'idle',
  'wave',
  'point',
  'cheer',
  'think',
  'oops',
] as const;

export type SpartyPose = (typeof SPARTY_POSE_IDS)[number];

export interface SpartyPoseFrames {
  frames: readonly (readonly string[])[];
  /** Milliseconds each frame shows; same length as `frames`. */
  durations: readonly number[];
}

export const SPARTY_POSES: Record<SpartyPose, SpartyPoseFrames> = {
  idle: {
    durations: [2400, 160],
    frames: [
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro....oYo...',
        '..........orRrrRrrRrro....oYo...',
        '...........orrdrrdrro.....oYo...',
        '............ordrrdro......ooo...',
        '............ordrrdro......oto...',
        '.............odrrdo.......oto...',
        '............oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '....odoyYyyyyyyyyyyyyyyYyoordo..',
        '....odobbbbbbbbbbbbbbbbbboordo..',
        '....odobooooooYbbYooooooboordo..',
        '....odobosowsoYbbYosowsoboordo..',
        '....odobosoosoYbbYosoosoboordo..',
        '....odobosoosoYbbYosoosoboordo..',
        '....odobyoooooYbbYoooooyboordo..',
        '.....oobbbyyyossssoyyybbboooo...',
        '.......obbbbboskksobbbbbo.oto...',
        '........oooooooooooooooooooto...',
        '....oooorrnnnnnnnnnnoowwwwwoo...',
        '....ossodnNNnnnnnnnnowBBBBBwo...',
        '....ossodnNnnnnnnnnowBBrrrBBwo..',
        '....ossodnnnnnnnnnnowBrrBrrBwo..',
        '.....oodobbbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro....oYo...',
        '..........orRrrRrrRrro....oYo...',
        '...........orrdrrdrro.....oYo...',
        '............ordrrdro......ooo...',
        '............ordrrdro......oto...',
        '.............odrrdo.......oto...',
        '............oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '....odoyYyyyyyyyyyyyyyyYyoordo..',
        '....odobbbbbbbbbbbbbbbbbboordo..',
        '....odobooooooYbbYooooooboordo..',
        '....odobossssoYbbYossssoboordo..',
        '....odobossssoYbbYossssoboordo..',
        '....odobosoosoYbbYosoosoboordo..',
        '....odobyoooooYbbYoooooyboordo..',
        '.....oobbbyyyossssoyyybbboooo...',
        '.......obbbbboskksobbbbbo.oto...',
        '........oooooooooooooooooooto...',
        '....oooorrnnnnnnnnnnoowwwwwoo...',
        '....ossodnNNnnnnnnnnowBBBBBwo...',
        '....ossodnNnnnnnnnnowBBrrrBBwo..',
        '....ossodnnnnnnnnnnowBrrBrrBwo..',
        '.....oodobbbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
    ],
  },
  wave: {
    durations: [280, 280],
    frames: [
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro....oYo...',
        '..........orRrrRrrRrro....oYo...',
        '...........orrdrrdrro.....oYo...',
        '............ordrrdro......ooo...',
        '............ordrrdro......oto...',
        '.............odrrdo.......oto...',
        '............oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '....odoyYyyyyyyyyyyyyyyYyoordo..',
        '..ooodobbbbbbbbbbbbbbbbbboordo..',
        '.ossodobooooooYbbYooooooboordo..',
        '.ossodobosoosoYbbYosoosoboordo..',
        '.ossodoboossooYbbYoossooboordo..',
        '..osodobossssoYbbYossssoboordo..',
        '..osodobyoooooYbbYoooooyboordo..',
        '..ossoobbbyyyossssoyyybbboooo...',
        '...oso.obbbbboskksobbbbbo.oto...',
        '...osso.oooooooooooooooooooto...',
        '....osoorrnnnnnnnnnnoowwwwwoo...',
        '......ordnNNnnnnnnnnowBBBBBwo...',
        '......ordnNnnnnnnnnowBBrrrBBwo..',
        '......ordnnnnnnnnnnowBrrBrrBwo..',
        '......odobbbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro....oYo...',
        '..........orRrrRrrRrro....oYo...',
        '...........orrdrrdrro.....oYo...',
        '............ordrrdro......ooo...',
        '............ordrrdro......oto...',
        '.............odrrdo.......oto...',
        '............oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '....odoyYyyyyyyyyyyyyyyYyoordo..',
        '.oo.odobbbbbbbbbbbbbbbbbboordo..',
        '.osoodobooooooYbbYooooooboordo..',
        '.ossodobosoosoYbbYosoosoboordo..',
        '..ossooboossooYbbYoossooboordo..',
        '..osodobossssoYbbYossssoboordo..',
        '..osodobyoooooYbbYoooooyboordo..',
        '..ossoobbbyyyossssoyyybbboooo...',
        '...oso.obbbbboskksobbbbbo.oto...',
        '...osso.oooooooooooooooooooto...',
        '....osoorrnnnnnnnnnnoowwwwwoo...',
        '......ordnNNnnnnnnnnowBBBBBwo...',
        '......ordnNnnnnnnnnowBBrrrBBwo..',
        '......ordnnnnnnnnnnowBrrBrrBwo..',
        '......odobbbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
    ],
  },
  point: {
    durations: [450, 450],
    frames: [
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro....oYo...',
        '..........orRrrRrrRrro....oYo...',
        '...........orrdrrdrro.....oYo...',
        '............ordrrdro......ooo...',
        '............ordrrdro......oto...',
        '.............odrrdo.......oto...',
        '............oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '....odoyYyyyyyyyyyyyyyyYyoordo..',
        '....odobbbbbbbbbbbbbbbbbboordo..',
        '....odobooooooYbbYooooooboordo..',
        '....odoboswssoYbbYoswssoboordo..',
        '....odobosossoYbbYosossoboordo..',
        '....odobosossoYbbYosossoboordo..',
        '....odobyoooooYbbYoooooyboordo..',
        '.....oobbbyyyossssoyyybbboooo...',
        '.......obbbbboskksobbbbbo.oto...',
        '.oo.....oooooooooooooooooooto...',
        '.soooooorrnnnnnnnnnnoowwwwwoo...',
        '.osssssodnNNnnnnnnnnowBBBBBwo...',
        '.ooooksoonNnnnnnnnnowBBrrrBBwo..',
        '....ooooonnnnnnnnnnowBrrBrrBwo..',
        '......odobbbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro....oYo...',
        '..........orRrrRrrRrro....oYo...',
        '...........orrdrrdrro.....oYo...',
        '............ordrrdro......ooo...',
        '............ordrrdro......oto...',
        '.............odrrdo.......oto...',
        '............oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '....odoyYyyyyyyyyyyyyyyYyoordo..',
        '....odobbbbbbbbbbbbbbbbbboordo..',
        '....odobooooooYbbYooooooboordo..',
        '....odoboswssoYbbYoswssoboordo..',
        '....odobosossoYbbYosossoboordo..',
        '....odobosossoYbbYosossoboordo..',
        '....odobyoooooYbbYoooooyboordo..',
        '.....oobbbyyyossssoyyybbboooo...',
        '.......obbbbboskksobbbbbo.oto...',
        'oo......oooooooooooooooooooto...',
        'sooooooorrnnnnnnnnnnoowwwwwoo...',
        'osssssordnNNnnnnnnnnowBBBBBwo...',
        'ooooksoodnNnnnnnnnnowBBrrrBBwo..',
        '...ooooodnnnnnnnnnnowBrrBrrBwo..',
        '......odobbbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
    ],
  },
  cheer: {
    durations: [260, 260],
    frames: [
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro....oYo...',
        '..........orRrrRrrRrro....oYo...',
        '...........orrdrrdrro.....oYo...',
        '............ordrrdro......ooo...',
        '............ordrrdro......oto...',
        '.............odrrdo.......oto...',
        '............oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '..ooodoyYyyyyyyyyyyyyyyYyoordo..',
        '.ossodobbbbbbbbbbbbbbbbbboordo..',
        '.ossodobooooooYbbYooooooboordo..',
        '..ooodobosoosoYbbYosoosoboordo..',
        '..osodoboossooYbbYoossooboordo..',
        '..osodobossssoYbbYossssoboordo..',
        '..ossoobyoooooYbbYoooooyboordo..',
        '...osoobbbyyyossssoyyybbboooo...',
        '...oss.obbbbboskksobbbbbo.oto...',
        '....os..oooooooooooooooooooto...',
        '.......orrnnnnnnnnnnoowwwwwoo...',
        '......ordnNNnnnnnnnnowBBBBBwo...',
        '......ordnNnnnnnnnnowBBrrrBBwo..',
        '......ordnnnnnnnnnnowBrrBrrBwo..',
        '......odobbbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
      [
        '..........oroRroRroRro....oYo...',
        '..........orRrrRrrRrro..y.oYo...',
        '...y.......orrdrrdrro..ywyoYo...',
        '..ywy.......ordrrdro....y.ooo...',
        '...y........ordrrdro......oto...',
        '.............odrrdo.......oto...',
        '............oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '..ooodoyYyyyyyyyyyyyyyyYyoordo..',
        '.ossodobbbbbbbbbbbbbbbbbboordo..',
        '.ossodobooooooYbbYooooooboordo..',
        '..ooodobosoosoYbbYosoosoboordo..',
        '..osodoboossooYbbYoossooboordo..',
        '..osodobossssoYbbYossssoboordo..',
        '..ossoobyoooooYbbYoooooyboordo..',
        '...osoobbbyyyossssoyyybbboooo...',
        '...oss.obbbbboskksobbbbbo.oto...',
        '....os..oooooooooooooooooooto...',
        '.......orrnnnnnnnnnnoowwwwwoo...',
        '......ordnNNnnnnnnnnowBBBBBwo...',
        '......ordnNnnnnnnnnowBBrrrBBwo..',
        '......ordnnnnnnnnnnowBrrBrrBwo..',
        '......odobbbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
        '................................',
      ],
    ],
  },
  think: {
    durations: [700, 700],
    frames: [
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro....oYo...',
        '..........orRrrRrrRrro....oYo...',
        '...........orrdrrdrro.....oYo...',
        '............ordrrdro......ooo...',
        '............ordrrdro......oto...',
        '.....oo......odrrdo.......oto...',
        '.....oo.....oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '....odoyYyyyyyyyyyyyyyyYyoordo..',
        '....odobbbbbbbbbbbbbbbbbboordo..',
        '....odobooooooYbbYooooooboordo..',
        '....odobossosoYbbYossosoboordo..',
        '....odobossosoYbbYossosoboordo..',
        '....odobossssoYbbYossssoboordo..',
        '....odobyoooooYbbYoooooyboordo..',
        '.....oobbbyyyossssoyyybbboooo...',
        '.......obbooooskksobbbbbo.oto...',
        '........oossssoooooooooooooto...',
        '.......orosssonnnnnnoowwwwwoo...',
        '......oroosoonnnnnnnowBBBBBwo...',
        '......oossoonnnnnnnowBBrrrBBwo..',
        '......oossonnnnnnnnowBrrBrrBwo..',
        '......odoobbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro....oYo...',
        '...oo.....orRrrRrrRrro....oYo...',
        '..owwo.....orrdrrdrro.....oYo...',
        '..owwo......ordrrdro......ooo...',
        '...oo.......ordrrdro......oto...',
        '.....oo......odrrdo.......oto...',
        '.....oo.....oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '....odoyYyyyyyyyyyyyyyyYyoordo..',
        '....odobbbbbbbbbbbbbbbbbboordo..',
        '....odobooooooYbbYooooooboordo..',
        '....odobossosoYbbYossosoboordo..',
        '....odobossosoYbbYossosoboordo..',
        '....odobossssoYbbYossssoboordo..',
        '....odobyoooooYbbYoooooyboordo..',
        '.....oobbbyyyossssoyyybbboooo...',
        '.......obbooooskksobbbbbo.oto...',
        '........oossssoooooooooooooto...',
        '.......orosssonnnnnnoowwwwwoo...',
        '......oroosoonnnnnnnowBBBBBwo...',
        '......oossoonnnnnnnowBBrrrBBwo..',
        '......oossonnnnnnnnowBrrBrrBwo..',
        '......odoobbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
    ],
  },
  oops: {
    durations: [420, 420],
    frames: [
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro..o.oYo...',
        '..........orRrrRrrRrro.oNooYo...',
        '...........orrdrrdrro..oNooYo...',
        '............ordrrdro....o.ooo...',
        '............ordrrdro......oto...',
        '.............odrrdo.......oto...',
        '............oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '....odoyYyyyyyyyyyyyyyyYyoordo..',
        '....odobbbbbbbbbbbbbbbbbboordo..',
        '...oodobooooooYbbYooooooboordo..',
        '...ssoobosowsoYbbYosowsoboordo..',
        '...ossobosoosoYbbYosoosoboordo..',
        '....osobosoosoYbbYosoosoboordo..',
        '....osobyoooooYbbYoooooyboordo..',
        '....ossobbyyyossssoyyybbboooo...',
        '.....osobbbbboskksobbbbbo.oto...',
        '.....ossoooooooooooooooooooto...',
        '......osrrnnnnnnnnnnoowwwwwoo...',
        '......ordnNNnnnnnnnnowBBBBBwo...',
        '......ordnNnnnnnnnnowBBrrrBBwo..',
        '......ordnnnnnnnnnnowBrrBrrBwo..',
        '......odobbbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
      [
        '..........o.oo.oo.oo.o.....o....',
        '..........oroRroRroRro....oYo...',
        '..........orRrrRrrRrro..o.oYo...',
        '...........orrdrrdrro..oNooYo...',
        '............ordrrdro...oNoooo...',
        '............ordrrdro....o.oto...',
        '.............odrrdo.......oto...',
        '............oYYbbbbo......oto...',
        '.........oooyyyyyyyyooo...oto...',
        '........oyyYYyyyyyyYYyyo..oto...',
        '....odroyyYyyyyyyyyyyYyyo.ordo..',
        '....odroyYyyyyyyyyyyyyYyo.ordo..',
        '....odoyYyyyyyyyyyyyyyyYyoordo..',
        '....odobbbbbbbbbbbbbbbbbboordo..',
        '...oodobooooooYbbYooooooboordo..',
        '...ssoobosowsoYbbYosowsoboordo..',
        '...ossobosoosoYbbYosoosoboordo..',
        '....osobosoosoYbbYosoosoboordo..',
        '....osobyoooooYbbYoooooyboordo..',
        '....ossobbyyyossssoyyybbboooo...',
        '.....osobbbbboskksobbbbbo.oto...',
        '.....ossoooooooooooooooooooto...',
        '......osrrnnnnnnnnnnoowwwwwoo...',
        '......ordnNNnnnnnnnnowBBBBBwo...',
        '......ordnNnnnnnnnnowBBrrrBBwo..',
        '......ordnnnnnnnnnnowBrrBrrBwo..',
        '......odobbbbbbbbbbowBrrBrrBwo..',
        '......oooybybybyybyowBrrBrrBwo..',
        '........oooooooooooowBBrrrBBwo..',
        '..........osso....osowBBBBBwo...',
        '.........obbbo....oboowwwwwoo...',
        '.........ooooo....oooooooooto...',
      ],
    ],
  },
};
