/**
 * `buildPlcLinkage` is shared by the QuizWidget, the Classroom add-on, the
 * LTI picker and the PLC page. It never creates a Google Sheet (D2).
 */

import { describe, it, expect } from 'vitest';
import type { Plc } from '@/types';
import { buildPlcLinkage } from '@/utils/plcLinkage';

const SELF_UID = 'teacher-uid';

function makePlc(overrides?: Partial<Plc>): Plc {
  return {
    id: 'plc-1',
    name: 'Math PLC',
    leadUid: SELF_UID,
    members: {},
    memberUids: [SELF_UID, 'peer-uid'],
    memberEmails: {
      [SELF_UID]: 'teacher@orono.k12.mn.us',
      'peer-uid': 'peer@orono.k12.mn.us',
    },
    sharedSheetUrl: null,
    createdAt: 0,
    updatedAt: 0,
    ...overrides,
  };
}

describe('buildPlcLinkage', () => {
  it('returns no linkage when no PLC is supplied', () => {
    expect(buildPlcLinkage(undefined)).toBeUndefined();
  });

  it('returns no linkage when the PLC snapshot has no name yet', () => {
    expect(buildPlcLinkage(makePlc({ name: '' }))).toBeUndefined();
  });

  it('builds id, name and the member email snapshot without a sheet', () => {
    const linkage = buildPlcLinkage(makePlc());
    expect(linkage).toEqual({
      id: 'plc-1',
      name: 'Math PLC',
      memberEmails: expect.arrayContaining([
        'teacher@orono.k12.mn.us',
        'peer@orono.k12.mn.us',
      ]),
    });
    expect(linkage).not.toHaveProperty('sheetUrl');
    expect(linkage).not.toHaveProperty('autoGenerated');
  });
});
