/**
 * Unit tests for `buildPlcLinkage` — the shared PLC-linkage builder used by
 * BOTH the QuizWidget assign flow and the Google Classroom add-on attach
 * path. Pins the contract so the two call sites can't drift:
 *   - no PLC                → no linkage, no error
 *   - manual sheet URL      → linkage with that URL, NOT auto-generated
 *   - auto-create success   → linkage with the created URL, autoGenerated:true
 *   - auto-create failure   → no linkage, error surfaced (assignment proceeds)
 *   - no token + no URL      → no linkage, no error (auto-create skipped)
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { Plc } from '@/types';

// Mock the Drive service so no real Sheets/Drive calls happen. `vi.hoisted`
// lets the spy be referenced inside the hoisted `vi.mock` factory (plain
// module-level consts aren't initialized when the factory runs).
const { createPlcSheetAndShare } = vi.hoisted(() => ({
  createPlcSheetAndShare: vi.fn(),
}));
vi.mock('@/utils/quizDriveService', () => ({
  QuizDriveService: class {
    createPlcSheetAndShare = createPlcSheetAndShare;
  },
}));

import { buildPlcLinkage } from '@/utils/plcLinkage';

const SELF_UID = 'teacher-uid';

function makePlc(overrides?: Partial<Plc>): Plc {
  return {
    id: 'plc-1',
    name: 'Math PLC',
    leadUid: SELF_UID,
    members: {},
    memberUids: [SELF_UID, 'peer-uid'],
    memberEmails: {
      [SELF_UID]: 'teacher@orono.k12.mn.us',
      'peer-uid': 'peer@orono.k12.mn.us',
    },
    sharedSheetUrl: null,
    createdAt: 0,
    updatedAt: 0,
    ...overrides,
  };
}

describe('buildPlcLinkage', () => {
  beforeEach(() => {
    createPlcSheetAndShare.mockReset();
  });

  it('returns no linkage and no error when no PLC is supplied', async () => {
    const result = await buildPlcLinkage({
      plc: undefined,
      quizTitle: 'Quiz',
      selfUid: SELF_UID,
      googleAccessToken: 'token',
    });
    expect(result.linkage).toBeUndefined();
    expect(result.error).toBeNull();
    expect(createPlcSheetAndShare).not.toHaveBeenCalled();
  });

  it('uses a manually-pasted sheet URL without auto-creating', async () => {
    const result = await buildPlcLinkage({
      plc: makePlc(),
      quizTitle: 'Quiz',
      selfUid: SELF_UID,
      googleAccessToken: 'token',
      manualSheetUrl: 'https://docs.google.com/spreadsheets/d/manual',
    });
    expect(createPlcSheetAndShare).not.toHaveBeenCalled();
    expect(result.error).toBeNull();
    expect(result.linkage).toEqual({
      id: 'plc-1',
      name: 'Math PLC',
      sheetUrl: 'https://docs.google.com/spreadsheets/d/manual',
      memberEmails: ['teacher@orono.k12.mn.us', 'peer@orono.k12.mn.us'],
    });
    // Manual URL is NOT system-generated.
    expect(result.linkage?.autoGenerated).toBeUndefined();
  });

  it('auto-creates a sheet (sharing with teammates) and flags it autoGenerated', async () => {
    createPlcSheetAndShare.mockResolvedValueOnce({
      url: 'https://docs.google.com/spreadsheets/d/auto',
      spreadsheetId: 'auto',
    });
    const result = await buildPlcLinkage({
      plc: makePlc(),
      quizTitle: 'Fractions Check',
      selfUid: SELF_UID,
      googleAccessToken: 'token',
    });
    expect(createPlcSheetAndShare).toHaveBeenCalledWith({
      plcName: 'Math PLC',
      quizTitle: 'Fractions Check',
      // Teammates only — self is excluded (already owns the sheet).
      memberEmailsToShareWith: ['peer@orono.k12.mn.us'],
    });
    expect(result.error).toBeNull();
    expect(result.linkage).toEqual({
      id: 'plc-1',
      name: 'Math PLC',
      sheetUrl: 'https://docs.google.com/spreadsheets/d/auto',
      memberEmails: ['teacher@orono.k12.mn.us', 'peer@orono.k12.mn.us'],
      autoGenerated: true,
    });
  });

  it('surfaces the error and yields no linkage when auto-create fails', async () => {
    createPlcSheetAndShare.mockRejectedValueOnce(new Error('Drive 403'));
    const result = await buildPlcLinkage({
      plc: makePlc(),
      quizTitle: 'Quiz',
      selfUid: SELF_UID,
      googleAccessToken: 'token',
    });
    expect(result.linkage).toBeUndefined();
    expect(result.error).toBeInstanceOf(Error);
    expect(result.error?.message).toBe('Drive 403');
  });

  it('skips auto-create (no linkage, no error) when there is no token and no manual URL', async () => {
    const result = await buildPlcLinkage({
      plc: makePlc(),
      quizTitle: 'Quiz',
      selfUid: SELF_UID,
      googleAccessToken: null,
    });
    expect(createPlcSheetAndShare).not.toHaveBeenCalled();
    expect(result.linkage).toBeUndefined();
    expect(result.error).toBeNull();
  });
});
